// Package rebalancer drives the daily Manthan portfolio rebalance.
//
// It runs as a manual CLI (no daemon, no schedule). Each invocation:
//   1. Discovers every active MANTHAN strategy across all users.
//   2. For each strategy, fetches REAL capital from the broker (fund-limit +
//      positions + holdings).
//   3. Loads the current portfolio snapshot + today's eligible signals.
//   4. Runs the EMA-cycle-aware allocator: each new candidate is sized by
//      `per_call × ema_target_for_index`, capped so cumulative deployment in
//      that index never exceeds today's EMA target percentage of capital.
//   5. Publishes approved entries as MANTHAN_ENTRY messages to the existing
//      `trade-signals` Kafka topic — trade-execution and rules-engine handle
//      the rest of the pipeline unchanged.
//
// The rebalancer is an alternate PRODUCER of MANTHAN_ENTRY messages (not a
// parallel order placer). All idempotency, CQRS, manual-interference and
// override safeguards we already built apply automatically.
package internal

import (
	"time"
)

// StrategyConfig is the slice of trading_db.strategies + child tables we need
// to drive a rebalance. Loaded once per strategy.
type StrategyConfig struct {
	StrategyID    string
	UserID        string
	StrategyName  string
	TradingMode   string  // PAPER | LIVE
	TotalCapital  float64 // initial capital (configured)
	MaxPositions  int     // 25 if TotalCapital ≤25L else 50
	StopLossPct   float64 // e.g. 20 (percent, not fraction)
	TrailingSLPct float64 // e.g. 2

	// Broker auth — fetched from user-config via gRPC (Phase 0.6a) so the
	// rebalancer can call fund-limit / position-book / holdings.
	BearerToken string
	AppID       string
	Source      string // WEB | AND | IOS
}

// CurrentCapital is what the broker says we actually have today, broken down
// for forensics. Sum of components is the figure the allocator uses.
type CurrentCapital struct {
	Cash             float64 // fund-limit AvailableMargin
	PositionsValue   float64 // sum(NetQty × LTP) over delivery rows in position-book
	HoldingsValue    float64 // sum(Qty × CurrentPrice) over holdings
	Total            float64 // Cash + PositionsValue + HoldingsValue
	Source           string  // "broker" | "db_fallback"
	DBStateSnapshot  float64 // manthan_portfolio_state.current_capital, for drift check
	BrokerFetchError error   // non-nil if we used db_fallback
	// Prices: live LTP per displayed symbol from position-book + holdings.
	// Used by the top-up phase to size additional buy quantity at current
	// market price (signal.latest_price is sheet-time, may be stale).
	Prices map[string]float64
}

// EligibleSignal is one row from signals_db.manthan_signals (today only).
type EligibleSignal struct {
	Symbol     string
	ISIN       string
	Industry   string
	MCapBucket string  // LARGE | MID | SMALL
	IndexName  string  // NIFTY50 | NFTYMCP150 | NTYSLCP250 | ...
	LatestPrice float64
	ATHClose    float64
	Week52High  float64
}

// PositionSummary is the per-strategy view of what's currently held — used
// for cap math (sector / mcap / index-deployed) and for the top-up phase
// (we need the parent signal_id + invested_amt to compute the gap to target).
type PositionSummary struct {
	SignalID    string // parent signal_id, used as TopUpForSignalID on top-up entries
	Symbol      string
	ISIN        string // needed by trade-execution to resolve the broker token on top-up
	Industry    string
	MCapBucket  string
	IndexName   string
	Quantity    int
	InvestedAmt float64
	Status      string // ACTIVE | PARTIAL_ACTIVE
}

// PortfolioSnapshot is everything the allocator needs to decide what to do.
type PortfolioSnapshot struct {
	Cfg              StrategyConfig
	Capital          CurrentCapital
	PerCall          float64              // Capital.Total ÷ Cfg.MaxPositions
	ActivePositions  []PositionSummary    // current holdings
	CooldownSymbols  map[string]float64   // symbol → reentry_below price
	OverrideSymbols  map[string]time.Time // symbol → user_override_until
	EMATargets       map[string]float64   // index → fraction (0..1)
	IndexDeployedPct map[string]float64   // index → already-deployed fraction of capital
	SectorCount      map[string]int       // industry → count of active positions
	BucketCount      map[string]int       // mcap bucket → count
	// LivePrices: symbol → current LTP from broker position-book. Used by
	// the top-up phase to size additional buy quantity at the latest price.
	// May be missing for symbols whose broker position-book row had ltp=0.
	LivePrices map[string]float64
}

// PlannedEntry is one new position the allocator wants to take.
type PlannedEntry struct {
	SignalID      string  // UUID generated by rebalancer
	Symbol        string
	ISIN          string
	IndexName     string
	Industry      string
	MCapBucket    string
	EntryPrice    float64 // = signal LatestPrice (broker MARKET will fill at ASK)
	Quantity      int32
	InvestedAmt   float64 // Quantity × EntryPrice (pre-cost estimate)
	StopLoss      float64 // EntryPrice × (1 − StopLossPct/100)
	EMAFraction   float64 // 0..1, the index target used for sizing
	Reason        string  // human-readable, for the dry-run summary

	// TopUpForSignalID — non-empty means this entry tops up an existing
	// position; trade-execution will skip its "already holding" duplicate
	// check, place a normal BUY at market, and on fill rules-engine's
	// projector will ADD qty + invested onto the parent manthan_positions
	// row instead of INSERT-ing a new row. Always empty for fresh entries.
	TopUpForSignalID string
}

// SkipReason tells you why a candidate was passed over.
type SkipReason struct {
	Symbol string
	Reason string
}

// AllocResult is the per-strategy output of one allocator pass.
type AllocResult struct {
	Cfg     StrategyConfig
	Planned []PlannedEntry
	TopUps  []PlannedEntry // top-ups go on the same wire as PlannedEntry, marked via TopUpForSignalID
	Skipped []SkipReason
	Capital CurrentCapital // for the summary line
	PerCall float64
}
