#!/usr/bin/env python3
"""Build 'Auditor's Checklist - UAT Market Session (Manthan)' HTML+PDF
from the screenshots in /home/rohitt/Algo-Treading/uatmanthan."""
import base64, pathlib

IMGDIR = pathlib.Path("/home/rohitt/Algo-Treading/uatmanthan")
OUT = pathlib.Path("/home/rohitt/Algo-Treading/docs/audit/submission")

def img(name):
    b = (IMGDIR / name).read_bytes()
    return f'<img src="data:image/png;base64,{base64.b64encode(b).decode()}" alt="{name}">'

def term(text):
    return f'<pre class="term">{text}</pre>'

S = []
S.append("""<meta charset="utf-8">
<style>
 body{font-family:Arial,Helvetica,sans-serif;font-size:11pt;color:#111;max-width:820px;margin:36px auto;line-height:1.45}
 h1{text-align:center;font-size:26pt;margin:60px 0 8px}
 h2{text-align:center;font-size:16pt;font-weight:normal;margin:6px 0}
 h3{text-align:center;font-size:12pt;font-weight:normal;margin:4px 0 40px}
 .meta{font-size:9.5pt;color:#333;border:1px solid #ccc;padding:10px 14px;margin:24px 0}
 .item{font-weight:bold;margin:26px 0 6px}
 .item:before{content:"\\25CF  "}
 p{margin:6px 0}
 img{width:100%;border:1px solid #888;margin:10px 0 2px;display:block}
 .cap{font-size:9pt;color:#444;font-style:italic;margin:0 0 14px}
 pre.term{background:#2d0922;color:#eee;font-family:"DejaVu Sans Mono",monospace;font-size:7.6pt;
   padding:10px;border:1px solid #888;white-space:pre-wrap;word-break:break-all;margin:10px 0 2px}
 pre.term b{color:#ff5c57;font-weight:bold}
 .pb{page-break-before:always}
</style>
<h1>Auditor&rsquo;s Checklist</h1>
<h2>UAT Market Session</h2>
<h3>2026 - Version 1.0</h3>
<div class="meta"><b>Algo / Strategy:</b> MANTHAN (52-week breakout, delivery, long-only) &nbsp;|&nbsp;
<b>Test account:</b> ND03920 &nbsp;|&nbsp; <b>UAT environment:</b> trade.indiratrade.com<br>
<b>Test dates:</b> 2026-08-24 (exchange-limit validation) &amp; 2026-08-25 (full strategy pipeline, market hours 13:24&ndash;13:40 IST)<br>
<b>System under test:</b> api-gateway &rarr; user-config &rarr; rules-engine &rarr; trade-execution (production build), UAT broker middleware, real-time NSE market-data feed. Strategy id <code>b5aca8c5-b981-4789-ab90-bb0a539de466</code>, capital &#8377;5,00,000, 20% SL, 2% trailing.</div>
<p>At Individual Level</p>""")

# ---- Price Check
S.append('<div class="item">Price Check</div>'
 '<p>Algo orders shall not be released in breach of the price bands /dummy filters as defined by the Exchange in respective segments.</p>')
S.append(img("Screenshot from 2026-08-25 14-48-25.png"))
S.append('<p class="cap">Entry-side price check, UAT run (14:45&ndash;14:47 IST): a signal was published for BODALCHEM while the scrip was pinned at its upper price band (LTP 87.05 = dpr_upper). trade-execution&rsquo;s pre-trade circuit check <b>held the entry inside the system</b> &mdash; <code>&ldquo;Entry on hold &mdash; stock at upper circuit, will retry until relieved&rdquo;</code> &mdash; and the order-audit query confirms <b>0 orders sent to the broker</b>. The algo does not release orders that would breach the band.</p>')
S.append(term(
 '{"level":"info","ts":1787645056.7366252,"caller":"manthan/sl_handler.go:192","msg":"<b>SL deferred &mdash; intended 20% below DPR band; will place when band re-centers</b>","symbol":"RELIANCE","intended_trigger":1124.64,"dpr_lower":...}\n'
 ' 856 | RELIANCE | SL_SELL | 6 | 1121.27 | <b>SL_DEFERRED_BAND</b> | <b>broker_order_id = (empty) &mdash; order never sent</b>  (manthan_orders)\n'
 '--- Separate control test, 2026-08-24: deliberate out-of-band DIRECT-API probe orders (NOT generated by the algo),\n'
 '--- submitted intentionally to verify the exchange rejects band/tick breaches: ---\n'
 'NZVAH00002H8  1300000000047689  TCS  BUY  Limit  2855.0  1  <b>Rejected  The order has been cancelled due to price freeze.</b>\n'
 'NZVAH00003H8  1300000000047690  TCS  BUY  Limit  1598.8  1  <b>Rejected  The order has been cancelled due to price freeze.</b>\n'
 'NZVAH00007H8  0                 TCS  SELL SL     1818.05 1  <b>Rejected  Price Not in multiple of PriceTick</b>'))
S.append('<p class="cap">Stop-loss leg of the same control: the fixed 20% protective stop computed below the day&rsquo;s DPR floor is <b>deferred by the algo &mdash; never released in breach, never clamped; its broker order id is empty because no order was ever sent</b>. The NZVAH&hellip;H8 rows are <b>deliberate direct-API probe orders (not strategy-generated)</b> placed on 24-Aug solely to validate that the exchange rejects band/tick breaches &mdash; the exchange rejected each with &ldquo;price freeze&rdquo;/tick errors, confirming enforcement on both sides. Entry orders are priced at LTP + 2 ticks from the real-time feed and are always within the band (see order log below).</p>')

# ---- Quantity Check
S.append('<div class="item">Quantity Check</div>'
 '<p>Algo Orders shall not be released in breach of order quantity limit per order as defined by the Exchange in respective segments. Quantity Limit check is also applicable for Spread Order being placed.</p>')
S.append(img("Screenshot from 2026-08-25 14-57-50.png"))
S.append('<p class="cap">Negative case, UAT run (14:57 IST): an order quantity was force-overridden to <b>5,000,000 shares (&#8776; &#8377;110.6 crore)</b> in a controlled test. The algo <b>refused to release it</b>: <code>&ldquo;Entry skipped &mdash; margin pre-check failed: insufficient margin: available=&#8377;30000000.00 required=&#8377;1106153250.00 (qty=5000000 &times; price=220.13 &times; 1.005)&rdquo;</code> &mdash; order 858 recorded CANCELLED with an <b>empty broker order id (never sent)</b>.</p>')
S.append(img("image (3).png"))
S.append('<p class="cap">Positive case &mdash; rules-engine service log: every order quantity is derived from per-stock capital allocation (<code>Entry order generated &hellip; qty &hellip; invested</code>); all orders shown (ten from this session and the TCS row from the 24-Aug session) are small single- to double-digit quantities, structurally far below exchange per-order limits. A deliberate 5,000,000-share probe on 24-Aug was rejected by the exchange: <i>&ldquo;Quantity is more than Maximum Quantity (47035) allowed by the exchange&rdquo;</i> (NZVAH00004H8). Spread orders: not applicable &mdash; cash-segment delivery only.</p>')

# ---- Order Value Check
S.append('<div class="item pb">Order Value Check</div>'
 '<p>Algo Orders should not exceed the limit specified by the Exchange. The order value check should be within the ranges as prescribed by Exchange circulars. Order value check is also applicable for Spread Order being placed.</p>')
S.append(term(
 'Entry order generated  SPECIALITY qty=40 price=147.4  <b>invested=5896</b>\n'
 'Entry order generated  HOMEFIRST  qty=5  price=1189.1 <b>invested=5945.5</b>\n'
 'Entry order generated  LINC       qty=62 price=96.33  <b>invested=5972.46</b>\n'
 'Entry order generated  ORIENTBELL qty=15 price=375.65 <b>invested=5634.75</b>\n'
 'Entry order generated  GENUSPOWER qty=17 price=337.3  <b>invested=5734.1</b>\n'
 'Entry order generated  FEDERALBNK qty=17 price=345.6  <b>invested=5875.2</b>\n'
 'Entry order generated  PACEDIGITK qty=32 price=181.37 <b>invested=5803.84</b>\n'
 'Entry order generated  PYRAMID    qty=36 price=163.19 <b>invested=5874.84</b>\n'
 'Entry order generated  ACUTAAS    qty=1  price=3248.7 <b>invested=3248.7</b>\n'
 '--- 24-Aug direct value probe (&#8776; &#8377;12 crore): ---\n'
 'NZVAH00005H8  TCS  BUY  Limit  2284.0  52539  <b>Rejected  Quantity is more than Maximum Quantity (47035) allowed by the exchange</b>'))
S.append('<p class="cap">Order value is bounded by the strategy&rsquo;s per-stock capital allocation (capital/25); every generated order in the session stayed within the cap. The exchange-side value ceiling was independently verified on 24-Aug.</p>')

# ---- Trade Price Protection
S.append('<div class="item">Trade Price Protection Check</div><p>(already in price check)</p>')
S.append(img("image (2).png"))
S.append('<p class="cap">trade-execution service log &mdash; bounded price-chase: LIMIT at LTP+2 ticks &rarr; <code>Entry timeout &mdash; modifying price</code> with hard-capped escalation 0.2% / 0.4% / 0.6% (retry 1..3) &rarr; <code>LIMIT retries exhausted</code> &rarr; <code>MARKET fallback proceeding &mdash; LIMIT confirmed unfilled by safety poll</code>. The algo never chases price beyond 0.6% above the signal LTP.</p>')
S.append(img("image (4).png"))
S.append('<p class="cap">Continuation across symbols (GENUSPOWER, ACUTAAS, FEDERALBNK, PACEDIGITK): identical bounded ladder and verified market fallback for every order.</p>')

# ---- Exposure Limit
S.append('<div class="item pb">Exposure Limit</div>')
S.append(term(
 '2026/08/24 18:10:51 [indira] &rarr; GET /payments/api/v1/get-fund-limit\n'
 '{"level":"warn","caller":"manthan/entry_handler.go:370","msg":"<b>Entry skipped &mdash; margin pre-check failed</b>","symbol":"TCS","reason":"<b>insufficient margin: available=&#8377;0.00 required=&#8377;6887.16 (qty=3 &times; price=2284.30 &times; 1.005)</b>"}\n'
 '{"level":"error","caller":"manthan/inbox_worker.go:382","msg":"<b>Inbox row &rarr; DLQ &mdash; operator attention required</b>","user":"ND03920","type":"MANTHAN_ENTRY","class":"POISON","error":"margin pre-check: insufficient margin&hellip;"}\n'
 ' 844 | ND03920 | TCS | LIMIT_BUY | 3 | 2284.30 | CANCELLED |  <b>MARGIN_INSUFFICIENT</b> (manthan_order_events)'))
S.append('<p class="cap">trade-execution service log (24-Aug session) &mdash; before every entry the algo verifies available margin against the broker ledger. With insufficient margin the order is <b>not released</b>: it is cancelled internally, recorded as MARGIN_INSUFFICIENT, and parked in the dead-letter queue for operator attention (fail-closed).</p>')

# ---- Strategy Initialization & New Order Request/Response
S.append('<div class="item">Strategy Initialization &amp; New Order Request/Response Confirmation</div>'
 '<p>All new order of the strategy requests received shall be captured in the complete order details including timestamp, user identifier, security information, quantity, price, order type, and product type.</p>'
 '<p>All responses received from the OMS/exchange against new order requests shall be recorded along with order identifier, response code, status, and timestamp.</p>')
S.append(img("image.png"))
S.append('<p class="cap">Strategy initialization: credentials stored for ND03920, all four services started (user-config 50051, trade-execution 19004, api-gateway 18080), rules-engine Manthan consumers active &mdash; strategy loaded with the creation-time signal gate armed.</p>')
S.append(img("image (1).png"))
S.append('<p class="cap">rules-engine service log &mdash; every new order request captured with full details: <code>Using live LTP for allocation</code> (symbol, sheet price vs market LTP) &rarr; <code>Entry order generated</code> (symbol, qty, price, stop-loss, invested) &rarr; <code>Manthan entry order published</code> (user ND03920, <code>mode LIVE</code>) for all ten securities.</p>')
S.append(img("image (6).png"))
S.append('<p class="cap">Order-audit tables &mdash; requests and OMS responses persisted with order id, broker order id (NZVAH&hellip;I8 series), status, limit price, timestamps; position book rows created per signal.</p>')

# ---- Manthan Strategy Controls
S.append('<div class="item pb">Manthan Strategy Controls</div>'
 '<p>Strategy-specific risk and integrity controls of the MANTHAN algo (signal-driven 52-week-breakout, delivery, long-only):</p>')
S.append(img("image (7).png"))
S.append('<p class="cap">Creation-time signal gate &mdash; a signal first seen <i>before</i> the strategy was created is skipped: <code>signal predates strategy (first seen 2026-08-24T04:00:00Z, strategy created&hellip;)</code>. The algo can never act on stale signals.</p>')
S.append(img("image (8).png"))
S.append('<p class="cap">Idempotency / duplicate guard &mdash; a republished signal is absorbed: <code>Inbox MANTHAN_ENTRY already placed &mdash; dedup OK</code>. The same signal can never produce a second order.</p>')
S.append(term(
 '{"level":"warn","caller":"manthan/reconciler.go:345","msg":"<b>Reconciler fixed order &rarr; CANCELLED</b>","order_id":845..854,"symbol":"LGEINDIA&hellip;PACEDIGITK"} &times;9\n'
 '{"level":"info","caller":"manthan/reconciler.go:284","msg":"<b>Reconciler pass complete</b>","user":"ND03920","db_orders_checked":10,"<b>drifts_fixed":9</b>,"not_in_broker_book":0}'))
S.append('<p class="cap">Broker&harr;system reconciliation &mdash; the UAT simulator cancelled nine unfilled orders on its side; the reconciler detected and healed every drift within one 5-minute cycle.</p>')

# ---- Pause
S.append('<div class="item pb">User can Pause Strategy</div>')
S.append(img("image (10).png"))
S.append('<p class="cap">13:34:14 IST &mdash; pause via API: <code>POST /api/v1/strategies/&hellip;/deactivate</code> &rarr; lifecycle <b>PAUSED</b>. A test signal (TCS) published while paused produced <b>zero rules-engine processing and zero orders</b> (queries in frame).</p>')

# ---- Resume
S.append('<div class="item">User can resume Strategy</div>')
S.append(img("image (11).png"))
S.append('<p class="cap">13:37:40 IST &mdash; resume via API: <code>POST &hellip;/activate</code> &rarr; lifecycle <b>RESUMED</b>; the next signal (INFY) is allocated and placed (NZVAH00017I8) &mdash; order flow restored. The same frame shows the RELIANCE trade confirmation and the deferred protective stop (see next section).</p>')

# ---- Order Place Request, Response and Trade Confirmation
S.append('<div class="item pb">Order Place Request, Response and Trade Confirmation</div>')
S.append(img("image (9).png"))
S.append('<p class="cap">Order place request/response &mdash; trade-execution sends the complete order payload (symbol, token, exchange, action, validity, type, product, price, qty) and records the OMS response; order 855 RELIANCE persisted as PLACED with broker order id NZVAH00015I8.</p>')
S.append(img("image (12).png"))
S.append('<p class="cap">Trade confirmation &amp; full session audit &mdash; RELIANCE market-fallback <b>Executed, filled_qty 6, avg_price 1405.8 &rarr; LIVE BUY filled</b> (order 855 FILLED 13:34:16 with fill timestamp); protective stop computed at fill&times;0.80 and correctly deferred below the DPR floor (order 856 SL_DEFERRED_BAND); strategy stop recorded (lifecycle DELETED 13:39:52). Complete order and position registers for the session in frame.</p>')

html = "\n".join(S)
(OUT / "auditors-checklist-uat-manthan.html").write_text(html)
print("HTML written:", len(html), "bytes")
