#!/usr/bin/env python3
"""Build 'Auditor's Checklist - Mock Market Session (Manthan)' HTML+PDF
from the screenshots in /home/rohitt/Algo-Treading/mockmanthan."""
import base64, pathlib

IMGDIR = pathlib.Path("/home/rohitt/Algo-Treading/mockmanthan")
OUT = pathlib.Path("/home/rohitt/Algo-Treading/docs/audit/submission")

def img(name):
    b = (IMGDIR / name).read_bytes()
    return f'<img src="data:image/png;base64,{base64.b64encode(b).decode()}" alt="{name}">'

def term(text):
    return f'<pre class="term">{text}</pre>'

S = []
S.append("""<meta charset="utf-8">
<style>
 body{font-family:Arial,Helvetica,sans-serif;font-size:11pt;color:#111;max-width:820px;margin:36px auto;line-height:1.45}
 h1{text-align:center;font-size:26pt;margin:60px 0 8px}
 h2{text-align:center;font-size:16pt;font-weight:normal;margin:6px 0}
 h3{text-align:center;font-size:12pt;font-weight:normal;margin:4px 0 40px}
 .meta{font-size:9.5pt;color:#333;border:1px solid #ccc;padding:10px 14px;margin:24px 0}
 .item{font-weight:bold;margin:26px 0 6px}
 .item:before{content:"\\25CF  "}
 p{margin:6px 0}
 img{width:100%;border:1px solid #888;margin:10px 0 2px;display:block;page-break-inside:avoid}
 .cap{font-size:9pt;color:#444;font-style:italic;margin:0 0 14px;page-break-before:avoid}
 pre.term{background:#2d0922;color:#eee;font-family:"DejaVu Sans Mono",monospace;font-size:7.6pt;
   padding:10px;border:1px solid #888;white-space:pre-wrap;word-break:break-all;margin:10px 0 2px;page-break-inside:avoid}
 pre.term b{color:#ff5c57;font-weight:bold}
</style>
<h1>Auditor&rsquo;s Checklist</h1>
<h2>Mock Market Session</h2>
<h3>2026 - Version 1.0</h3>
<div class="meta"><b>Algo / Strategy:</b> MANTHAN (52-week breakout, delivery, long-only) &nbsp;|&nbsp;
<b>Member:</b> Indira Securities Pvt. Ltd.<br>
<b>Test session:</b> NSE/BSE Mock Trading Session, Saturday 2026-08-22 &nbsp;|&nbsp; <b>Test accounts:</b> S4450 (strategy pipeline) and ND03920 (fresh strategy lifecycle)<br>
<b>System under test:</b> production stack (api-gateway &rarr; user-config &rarr; rules-engine &rarr; trade-execution) on the Manthan production server, broker middleware, exchange mock session. Order-ID series <code>NZWKE&hellip;F8</code> (ND03920) / <code>NYMZX&hellip;F8</code> (S4450) with exchange order numbers.<br>
<b>Evidence:</b> every figure is a terminal screenshot of <code>grep</code>s run on the production service logs (pm2, timestamps in UTC; IST = UTC+5:30) and of the production order-audit database, captured during the session.</div>
<p>At Individual Level</p>""")

# ---- Price Check
S.append('<div class="item">Price Check</div>'
 '<p>Algo orders shall not be released in breach of the price bands /dummy filters as defined by the Exchange in respective segments.</p>')
S.append(img("image (35).png"))
S.append('<p class="cap">Negative case, production server log (08:05 UTC = 13:35 IST): AXISBANK signalled while pinned at its upper price band (LTP = dpr_upper). The pre-trade circuit check <b>held the entry inside the system</b> for every subscribed user &mdash; <code>&ldquo;Entry on hold &mdash; stock at upper circuit, will retry until relieved&rdquo;</code> &mdash; no order was released.</p>')
S.append(img("image (36).png"))
S.append('<p class="cap">Order-audit confirmation for the same case: <b>0 AXISBANK order rows, 0 broker calls</b> &mdash; the breach candidate never left the system.</p>')
S.append(img("image (38).png"))
S.append('<p class="cap">The held signals are parked in the inbox with <code>class=&ldquo;UPPER_CIRCUIT&rdquo;</code> and re-checked on a 180-second retry cycle &mdash; the algo waits for the band to relieve instead of forcing an order through.</p>')
S.append(img("image (24).png"))
S.append('<p class="cap">Stop-loss leg of the price check: the fixed 20% protective stop for the RELIANCE fill computes to 1262.56, below the day&rsquo;s DPR floor 1381.80 &mdash; <code>&ldquo;SL deferred &mdash; intended 20% below DPR band; will place when band re-centers&rdquo;</code>. The order is <b>deferred, never clamped, never released in breach</b>.</p>')
S.append(img("image (25).png"))
S.append('<p class="cap">The deferred stop recorded as <code>SL_DEFERRED_BAND</code> (intended=1262.56 &lt; dpr_lower=1381.80) with an <b>empty broker order id &mdash; no order was ever sent</b>.</p>')
S.append(img("image (29).png"))
S.append('<p class="cap">Exchange-side confirmation via <b>deliberate out-of-band DIRECT-API probe orders (NOT generated by the algo)</b>, submitted intentionally to verify enforcement on both sides: BSE rejected with <i>&ldquo;LIMIT PRICE: 400 NOT EQUAL TO CLOSING PRICE: 292&rdquo;</i> and NSE with <i>&ldquo;The order has been cancelled due to price freeze.&rdquo;</i></p>')

# ---- Quantity Check
S.append('<div class="item">Quantity Check</div>'
 '<p>Algo Orders shall not be released in breach of order quantity limit per order as defined by the Exchange in respective segments. Quantity Limit check is also applicable for Spread Order being placed.</p>')
S.append(img("image (39).png"))
S.append('<p class="cap">Negative case, production server log (08:07:59 UTC = 13:37:59 IST): in a controlled test the CUB order quantity was force-overridden to <b>5,000,000 shares (&#8776; &#8377;111.93 crore)</b>. The algo <b>refused to release it</b>: <code>&ldquo;Entry skipped &mdash; margin pre-check failed: insufficient margin: available=&#8377;2011973.00 required=&#8377;1119318750.00 (qty=5000000 &times; price=222.75 &times; 1.005)&rdquo;</code>.</p>')
S.append(img("image (41).png"))
S.append('<p class="cap">The refused orders recorded as <code>MARGIN_INSUFFICIENT</code>, PENDING &rarr; CANCELLED, with the full computed requirement in the audit detail &mdash; <b>empty broker order id (never sent)</b>.</p>')
S.append(img("image (44).png"))
S.append('<p class="cap">Exchange-side confirmation via <b>deliberate DIRECT-API probe orders (NOT algo-generated)</b> from the mock-session order book: the 5,000,000-share probe (NYMZX002A6F8) and the &#8776; &#8377;12 crore probe (NYMZX002A7F8, 46,049 &times; 2605.90) both rejected &mdash; <i>&ldquo;Quantity is more than Maximum Quantity (43417) allowed by the exchange&rdquo;</i>; also in frame: price-freeze rejections, the tick-size rejection (<i>&ldquo;Price Not in multiple of PriceTick&rdquo;</i>), and a 1-share Market probe Executed. Spread orders: not applicable &mdash; cash-segment delivery only.</p>')
S.append(img("image (42).png"))
S.append('<p class="cap">Test integrity: the quantity-override test flag was removed immediately after the negative test (service restarted with <code>MANTHAN_TEST_QTY=1</code>, verified from the running process environment).</p>')

# ---- Order Value Check
S.append('<div class="item">Order Value Check</div>'
 '<p>Algo Orders should not exceed the limit specified by the Exchange. The order value check should be within the ranges as prescribed by Exchange circulars. Order value check is also applicable for Spread Order being placed.</p>')
S.append(img("image (17).png"))
S.append('<p class="cap">Order value is bounded structurally: the allocator sizes every order from per-stock capital allocation (capital/25) &mdash; <code>manthan_signal_decisions</code> records the intended investment per dispatched signal, keeping every order value far below exchange ceilings. The exchange-side value cap was independently verified with the &#8776; &#8377;12 crore direct probe above (NYMZX002A7F8, rejected).</p>')

# ---- Trade Price Protection
S.append('<div class="item">Trade Price Protection Check</div><p>(already in price check)</p>')
S.append(img("image (21).png"))
S.append('<p class="cap">Bounded price-chase on the RELIANCE entry: WSS confirms the resting LIMIT (<code>PENDING</code>) &rarr; <code>&ldquo;Entry timeout &mdash; modifying price&rdquo;</code> with hard-capped escalation (<code>retry 1, drift 0.45%, escalation 0.20%</code>) &rarr; modify-order request/response at the protected price. The algo never chases price beyond the capped ladder (0.2% / 0.4% / 0.6%, then market fallback).</p>')

# ---- Exposure Limit
S.append('<div class="item">Exposure Limit</div>')
S.append(img("image (18).png"))
S.append('<p class="cap">Positive case: before every entry the algo fetches the broker ledger (<code>GET /payments/api/v1/get-fund-limit &rarr; availableMargin</code>) and releases the order only when margin covers it (RELIANCE entry, margin OK).</p>')
S.append(img("image (43).png"))
S.append('<p class="cap">Negative case, full pipeline in one frame: signal queued &rarr; inbox claimed &rarr; quantity override (test) &rarr; fund-limit fetched (<code>availableMargin=2011973.0</code>) &rarr; <code>&ldquo;Entry skipped &mdash; margin pre-check failed&rdquo;</code> &rarr; <code>&ldquo;Inbox row &rarr; DLQ &mdash; operator attention required&rdquo;</code> (<code>class=POISON</code>). With insufficient margin the order is <b>not released</b> and the row is parked for operator attention (fail-closed).</p>')

# ---- Strategy Initialization & New Order Request/Response
S.append('<div class="item">Strategy Initialization &amp; New Order Request/Response Confirmation</div>'
 '<p>All new order of the strategy requests received shall be captured in the complete order details including timestamp, user identifier, security information, quantity, price, order type, and product type.</p>'
 '<p>All responses received from the OMS/exchange against new order requests shall be recorded along with order identifier, response code, status, and timestamp.</p>')
S.append(img("image (14).png"))
S.append('<p class="cap">Strategy creation captured across all four service layers in the service logs (06:59:11 UTC = 12:29:11 IST): api-gateway <code>POST /api/v1/strategies</code> &rarr; user-config <code>stored Indira credentials</code> &rarr; rules-engine <code>&ldquo;MANTHAN strategy created &mdash; triggering catch-up&rdquo;</code>.</p>')
S.append(img("image (15).png"))
S.append('<p class="cap">The creation persisted: <code>strategies</code> row (ND03920, LIVE, MANTHAN) and lifecycle event <code>DEPLOYED {&quot;capital&quot;: 500000}</code>.</p>')
S.append(img("image (16).png"))
S.append('<p class="cap">New order request capture, rules-engine log: <code>&ldquo;Using live LTP for allocation&rdquo;</code> (symbol, sheet price vs market LTP) &rarr; <code>&ldquo;Entry order generated&rdquo;</code> (symbol, qty, price, stop-loss, invested) &mdash; every order request carries full details.</p>')
S.append(img("image (19).png"))
S.append('<p class="cap">OMS request/response capture, trade-execution log: complete order payload (<code>symbol, excToken, exc, ordAction, ordValidity, ordType, prdType, limitPrice, qty</code>) and the broker response <code>{&quot;ordId&quot;:&quot;NZWKE00001F8&quot;,&quot;ordStatus&quot;:&quot;Requested&quot;}</code> with timestamps.</p>')
S.append(img("image (20).png"))
S.append('<p class="cap">Every request and response persisted to the order-audit tables: order row with broker order id, status, prices and timestamps (order 8915, FILLED).</p>')

# ---- Manthan Strategy Controls
S.append('<div class="item">Manthan Strategy Controls</div>'
 '<p>Strategy-specific risk and integrity controls of the MANTHAN algo (signal-driven 52-week-breakout, delivery, long-only):</p>')
S.append(img("image (48).png"))
S.append('<p class="cap">Market-hours gate &amp; fresh lifecycle (08:28:27 UTC = 13:58:27 IST): a second strategy deployed during the session logs <code>&ldquo;Strategy created outside market hours &mdash; deferring entries to next open (no catch-up now)&rdquo;</code> (Saturday); when the mock feed then delivered a signal (IIFL), the entry was placed and filled (order 8969, NZWKE00017F8) and the protective stop placed (order 8970, NZWKE00018F8).</p>')
S.append(img("image (30).png"))
S.append(img("image (31).png"))
S.append('<p class="cap">Hard 20% protective stop, placed at the broker when in-band: IIFL SL-L SELL placed at trigger 555.10 &mdash; <b>exactly fill &times; 0.80</b>, never widened, never clamped (broker id NZWKE0000AF8; event rows above).</p>')
S.append(img("image (45).png"))
S.append('<p class="cap">Trailing stop (2% step), band-aware: rules-engine <code>&ldquo;Trailing SL updated&rdquo;</code> for IPCALAB (07:33:57 UTC) &mdash; old_sl 1567.20 &rarr; new_sl 1780.80 = high 2226 &times; 0.80; because the new level was outside the day&rsquo;s band the trail was <b>recorded and deferred</b> (<code>SL_DEFERRED_TRAIL &mdash; &ldquo;placement awaits band via daily replay&rdquo;</code>), not forced through.</p>')
S.append(term(
 '2026-08-22T06:31:18: {"level":"warn","caller":"manthan/reconciler.go:345","msg":"<b>Reconciler fixed order &rarr; CANCELLED</b>","order_id":8861,"symbol":"IPCALAB","broker_order_id":"NYMZX0028BF8","broker_status":"Cancelled"}\n'
 '2026-08-22T06:31:18: {"level":"info","caller":"manthan/reconciler.go:284","msg":"<b>Reconciler pass complete</b>","user":"S4450","db_orders_checked":1,"<b>drifts_fixed":1</b>,"not_in_broker_book":0}\n'
 '2026-08-22T08:01:34: {"level":"warn","caller":"manthan/reconciler.go:345","msg":"<b>Reconciler fixed order &rarr; CANCELLED</b>","order_id":8937,"symbol":"IIFL","broker_order_id":"NZWKE0000CF8","broker_status":"Rejected"}\n'
 '2026-08-22T08:01:34: {"level":"warn","caller":"manthan/reconciler.go:345","msg":"<b>Reconciler fixed order &rarr; CANCELLED</b>","order_id":8936,"symbol":"IIFL","broker_order_id":"NZWKE0000BF8","broker_status":"Rejected"}\n'
 '2026-08-22T08:01:34: {"level":"info","caller":"manthan/reconciler.go:284","msg":"<b>Reconciler pass complete</b>","user":"ND03920","db_orders_checked":6,"<b>drifts_fixed":2</b>,"not_in_broker_book":0}'))
S.append('<p class="cap">Broker&harr;system reconciliation (production service log, same session): orders cancelled/rejected on the broker side are detected and healed within one 5-minute cycle &mdash; the order-audit database can never drift silently from the exchange book.</p>')

# ---- Pause
S.append('<div class="item">User can Pause Strategy</div>')
S.append(img("image (47).png"))
S.append('<p class="cap">Pause via API, first strategy (08:19:19 UTC = 13:49:19 IST): gateway <code>POST /api/v1/strategies/&hellip;/deactivate</code> &rarr; <code>strategies.active=f</code> &rarr; lifecycle <b>PAUSED</b>.</p>')
S.append(img("image (51).png"))
S.append('<p class="cap">Pause repeated on the second strategy (08:32:23 UTC = 14:02:23 IST): <code>/deactivate</code> &rarr; <code>active=f, version 2</code> &rarr; lifecycle <b>PAUSED {&quot;positions_exited&quot;: 0}</b>.</p>')
S.append(img("image (50).png"))
S.append('<p class="cap">While-paused proof: a signal (CUB) published one minute later was processed for other subscribed users but produced <b>zero rules-engine processing and zero orders for the paused strategy</b> (0-rows query in frame).</p>')

# ---- Resume
S.append('<div class="item">User can resume Strategy</div>')
S.append(img("image (52).png"))
S.append('<p class="cap">Resume via API (08:35:10 UTC = 14:05:10 IST): <code>POST &hellip;/activate</code> &rarr; <code>active=t, version 3</code> &rarr; lifecycle <b>RESUMED</b>; the next signal (NRBBEARING, 08:35:32) was allocated and placed within one second &mdash; order 8974 PLACED &mdash; order flow restored.</p>')

# ---- Order Place Request, Response and Trade Confirmation
S.append('<div class="item">Order Place Request, Response and Trade Confirmation</div>')
S.append(img("image (22).png"))
S.append('<p class="cap">Trade confirmation, RELIANCE (12:59 IST): <code>&ldquo;LIVE BUY filled&rdquo;</code> at 1578.20 after the protected price-chase.</p>')
S.append(img("image (23).png"))
S.append('<p class="cap">Complete audited lifecycle for the same order (8915): PLACED &rarr; MODIFIED (bounded escalation) &rarr; FILLED <code>&ldquo;WSS fill confirmed&rdquo;</code>, with prices, quantities and timestamps.</p>')
S.append(img("image (28).png"))
S.append('<p class="cap">Exchange order-book confirmation: the RELIANCE rows with broker order id and exchange order number (exchOrdId 1310000014940827).</p>')
S.append(img("image (26).png"))
S.append('<p class="cap">Position book updated from the confirmed fill: RELIANCE ACTIVE with entry price, stop level and high-water mark.</p>')
S.append(img("image (49).png"))
S.append('<p class="cap">Second full chain in one frame (IIFL, 08:31 UTC = 14:01 IST): place-order request/response (<code>NZWKE00017F8 Requested</code>) &rarr; <code>&ldquo;LIVE BUY filled&rdquo;</code> avg 694 &rarr; protective SL-L SELL placed at trigger 555.20 = fill &times; 0.80 (<code>NZWKE00018F8</code>) &rarr; audited events (PLACED / FILL &ldquo;WSS fill confirmed&rdquo; / SL_PLACED) &rarr; position ACTIVE.</p>')

# ---- Stop
S.append('<div class="item">User can Stop Strategy (square-off / delete)</div>')
S.append(img("image (54).png"))
S.append('<p class="cap">Stop via API (08:43:52 UTC = 14:13:52 IST): DeleteStrategy returns <code>success=true &ldquo;Strategy deleted successfully&rdquo;</code>; force-exit sweep runs (<code>0 exitable positions</code> in the mock book) and the strategy is marked deleted (<code>active=f, deleted_at set</code>) with the full lifecycle trail DEPLOYED &rarr; PAUSED &rarr; RESUMED &rarr; <b>DELETED</b>. Final audit tables in frame &mdash; note order 8971 <code>SL_SELL_AMO</code> (NZWKE00019F8): the end-of-day AMO protective stop was armed automatically before the stop, so open positions remain stop-protected.</p>')

# ---- Annexure
S.append('<div class="item">Annexure &mdash; Control-case registry</div>')
S.append(img("image (46).png"))
S.append('<p class="cap">Registry of the deliberate DIRECT-API control probes (A1&ndash;A7: resting limit, price-band high/low, tick-size, quantity limit, order value, market entry, 20% GTC stop) with their order ids, prices and exchange verdicts, and the holdings snapshot after the session. These probes are test instruments only &mdash; none were generated by the algo.</p>')

html = "\n".join(S)
(OUT / "auditors-checklist-mock-manthan.html").write_text(html)
print("HTML written:", len(html), "bytes")
