// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/common/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Order types
type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED      OrderType = 0
	OrderType_ORDER_TYPE_MARKET           OrderType = 1
	OrderType_ORDER_TYPE_LIMIT            OrderType = 2
	OrderType_ORDER_TYPE_STOP_LOSS        OrderType = 3
	OrderType_ORDER_TYPE_STOP_LOSS_MARKET OrderType = 4
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "ORDER_TYPE_MARKET",
		2: "ORDER_TYPE_LIMIT",
		3: "ORDER_TYPE_STOP_LOSS",
		4: "ORDER_TYPE_STOP_LOSS_MARKET",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED":      0,
		"ORDER_TYPE_MARKET":           1,
		"ORDER_TYPE_LIMIT":            2,
		"ORDER_TYPE_STOP_LOSS":        3,
		"ORDER_TYPE_STOP_LOSS_MARKET": 4,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_common_common_proto_enumTypes[0].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_api_proto_common_common_proto_enumTypes[0]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_common_common_proto_rawDescGZIP(), []int{0}
}

// Order side
type OrderSide int32

const (
	OrderSide_ORDER_SIDE_UNSPECIFIED OrderSide = 0
	OrderSide_ORDER_SIDE_BUY         OrderSide = 1
	OrderSide_ORDER_SIDE_SELL        OrderSide = 2
)

// Enum value maps for OrderSide.
var (
	OrderSide_name = map[int32]string{
		0: "ORDER_SIDE_UNSPECIFIED",
		1: "ORDER_SIDE_BUY",
		2: "ORDER_SIDE_SELL",
	}
	OrderSide_value = map[string]int32{
		"ORDER_SIDE_UNSPECIFIED": 0,
		"ORDER_SIDE_BUY":         1,
		"ORDER_SIDE_SELL":        2,
	}
)

func (x OrderSide) Enum() *OrderSide {
	p := new(OrderSide)
	*p = x
	return p
}

func (x OrderSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderSide) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_common_common_proto_enumTypes[1].Descriptor()
}

func (OrderSide) Type() protoreflect.EnumType {
	return &file_api_proto_common_common_proto_enumTypes[1]
}

func (x OrderSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderSide.Descriptor instead.
func (OrderSide) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_common_common_proto_rawDescGZIP(), []int{1}
}

// Order status
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED    OrderStatus = 0
	OrderStatus_ORDER_STATUS_RECEIVED       OrderStatus = 1
	OrderStatus_ORDER_STATUS_VALIDATED      OrderStatus = 2
	OrderStatus_ORDER_STATUS_PENDING        OrderStatus = 3
	OrderStatus_ORDER_STATUS_SUBMITTED      OrderStatus = 4
	OrderStatus_ORDER_STATUS_FILLED         OrderStatus = 5
	OrderStatus_ORDER_STATUS_PARTIAL_FILLED OrderStatus = 6
	OrderStatus_ORDER_STATUS_REJECTED       OrderStatus = 7
	OrderStatus_ORDER_STATUS_CANCELLED      OrderStatus = 8
	OrderStatus_ORDER_STATUS_FAILED         OrderStatus = 9
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_RECEIVED",
		2: "ORDER_STATUS_VALIDATED",
		3: "ORDER_STATUS_PENDING",
		4: "ORDER_STATUS_SUBMITTED",
		5: "ORDER_STATUS_FILLED",
		6: "ORDER_STATUS_PARTIAL_FILLED",
		7: "ORDER_STATUS_REJECTED",
		8: "ORDER_STATUS_CANCELLED",
		9: "ORDER_STATUS_FAILED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED":    0,
		"ORDER_STATUS_RECEIVED":       1,
		"ORDER_STATUS_VALIDATED":      2,
		"ORDER_STATUS_PENDING":        3,
		"ORDER_STATUS_SUBMITTED":      4,
		"ORDER_STATUS_FILLED":         5,
		"ORDER_STATUS_PARTIAL_FILLED": 6,
		"ORDER_STATUS_REJECTED":       7,
		"ORDER_STATUS_CANCELLED":      8,
		"ORDER_STATUS_FAILED":         9,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_common_common_proto_enumTypes[2].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_api_proto_common_common_proto_enumTypes[2]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_common_common_proto_rawDescGZIP(), []int{2}
}

// Sentiment types
type Sentiment int32

const (
	Sentiment_SENTIMENT_UNSPECIFIED Sentiment = 0
	Sentiment_SENTIMENT_POSITIVE    Sentiment = 1
	Sentiment_SENTIMENT_NEUTRAL     Sentiment = 2
	Sentiment_SENTIMENT_NEGATIVE    Sentiment = 3
)

// Enum value maps for Sentiment.
var (
	Sentiment_name = map[int32]string{
		0: "SENTIMENT_UNSPECIFIED",
		1: "SENTIMENT_POSITIVE",
		2: "SENTIMENT_NEUTRAL",
		3: "SENTIMENT_NEGATIVE",
	}
	Sentiment_value = map[string]int32{
		"SENTIMENT_UNSPECIFIED": 0,
		"SENTIMENT_POSITIVE":    1,
		"SENTIMENT_NEUTRAL":     2,
		"SENTIMENT_NEGATIVE":    3,
	}
)

func (x Sentiment) Enum() *Sentiment {
	p := new(Sentiment)
	*p = x
	return p
}

func (x Sentiment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sentiment) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_common_common_proto_enumTypes[3].Descriptor()
}

func (Sentiment) Type() protoreflect.EnumType {
	return &file_api_proto_common_common_proto_enumTypes[3]
}

func (x Sentiment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sentiment.Descriptor instead.
func (Sentiment) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_common_common_proto_rawDescGZIP(), []int{3}
}

// Exchange types
type Exchange int32

const (
	Exchange_EXCHANGE_UNSPECIFIED Exchange = 0
	Exchange_EXCHANGE_NSE         Exchange = 1
	Exchange_EXCHANGE_BSE         Exchange = 2
)

// Enum value maps for Exchange.
var (
	Exchange_name = map[int32]string{
		0: "EXCHANGE_UNSPECIFIED",
		1: "EXCHANGE_NSE",
		2: "EXCHANGE_BSE",
	}
	Exchange_value = map[string]int32{
		"EXCHANGE_UNSPECIFIED": 0,
		"EXCHANGE_NSE":         1,
		"EXCHANGE_BSE":         2,
	}
)

func (x Exchange) Enum() *Exchange {
	p := new(Exchange)
	*p = x
	return p
}

func (x Exchange) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Exchange) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_common_common_proto_enumTypes[4].Descriptor()
}

func (Exchange) Type() protoreflect.EnumType {
	return &file_api_proto_common_common_proto_enumTypes[4]
}

func (x Exchange) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Exchange.Descriptor instead.
func (Exchange) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_common_common_proto_rawDescGZIP(), []int{4}
}

// Position sizing strategy
type PositionSizing int32

const (
	PositionSizing_POSITION_SIZING_UNSPECIFIED PositionSizing = 0
	PositionSizing_POSITION_SIZING_FIXED       PositionSizing = 1 // Fixed quantity
	PositionSizing_POSITION_SIZING_PERCENTAGE  PositionSizing = 2 // Percentage of capital
	PositionSizing_POSITION_SIZING_RISK_BASED  PositionSizing = 3 // Based on risk amount
)

// Enum value maps for PositionSizing.
var (
	PositionSizing_name = map[int32]string{
		0: "POSITION_SIZING_UNSPECIFIED",
		1: "POSITION_SIZING_FIXED",
		2: "POSITION_SIZING_PERCENTAGE",
		3: "POSITION_SIZING_RISK_BASED",
	}
	PositionSizing_value = map[string]int32{
		"POSITION_SIZING_UNSPECIFIED": 0,
		"POSITION_SIZING_FIXED":       1,
		"POSITION_SIZING_PERCENTAGE":  2,
		"POSITION_SIZING_RISK_BASED":  3,
	}
)

func (x PositionSizing) Enum() *PositionSizing {
	p := new(PositionSizing)
	*p = x
	return p
}

func (x PositionSizing) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PositionSizing) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_common_common_proto_enumTypes[5].Descriptor()
}

func (PositionSizing) Type() protoreflect.EnumType {
	return &file_api_proto_common_common_proto_enumTypes[5]
}

func (x PositionSizing) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PositionSizing.Descriptor instead.
func (PositionSizing) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_common_common_proto_rawDescGZIP(), []int{5}
}

// Timestamp message for consistent time representation
type Timestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seconds       int64                  `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"` // Seconds since epoch
	Nanos         int32                  `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`     // Nanoseconds component
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_api_proto_common_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_api_proto_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *Timestamp) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Timestamp) GetNanos() int32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

// Pagination request parameters
type PaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                           // Page number (1-indexed)
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // Items per page (default: 10, max: 100)
	SortBy        string                 `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`          // Field to sort by
	SortOrder     string                 `protobuf:"bytes,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"` // "asc" or "desc"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_api_proto_common_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_common_common_proto_rawDescGZIP(), []int{1}
}

func (x *PaginationRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginationRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *PaginationRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

// Pagination response metadata
type PaginationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalItems    int64                  `protobuf:"varint,3,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	HasNext       bool                   `protobuf:"varint,5,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	HasPrevious   bool                   `protobuf:"varint,6,opt,name=has_previous,json=hasPrevious,proto3" json:"has_previous,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationResponse) Reset() {
	*x = PaginationResponse{}
	mi := &file_api_proto_common_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResponse) ProtoMessage() {}

func (x *PaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResponse.ProtoReflect.Descriptor instead.
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_common_common_proto_rawDescGZIP(), []int{2}
}

func (x *PaginationResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginationResponse) GetTotalItems() int64 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *PaginationResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *PaginationResponse) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *PaginationResponse) GetHasPrevious() bool {
	if x != nil {
		return x.HasPrevious
	}
	return false
}

// Generic error details
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`       // Error code (e.g., "INVALID_INPUT", "NOT_FOUND")
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Human-readable error message
	Details       []string               `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"` // Additional error details
	Timestamp     *Timestamp             `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_api_proto_common_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_api_proto_common_common_proto_rawDescGZIP(), []int{3}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() []string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Error) GetTimestamp() *Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Generic status response
type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_proto_common_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_common_common_proto_rawDescGZIP(), []int{4}
}

func (x *StatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StatusResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Empty message for void returns
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_proto_common_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_proto_common_common_proto_rawDescGZIP(), []int{5}
}

// Stock information
type Stock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockCode     int64                  `protobuf:"varint,1,opt,name=stock_code,json=stockCode,proto3" json:"stock_code,omitempty"` // Stock code (e.g., 517170)
	Exchange      string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`                     // Exchange (NSE/BSE)
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`                         // Trading symbol (e.g., "EDVENSWA")
	Isin          string                 `protobuf:"bytes,4,opt,name=isin,proto3" json:"isin,omitempty"`                             // ISIN code (e.g., "INE125G01014")
	CompanyName   string                 `protobuf:"bytes,5,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stock) Reset() {
	*x = Stock{}
	mi := &file_api_proto_common_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stock) ProtoMessage() {}

func (x *Stock) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stock.ProtoReflect.Descriptor instead.
func (*Stock) Descriptor() ([]byte, []int) {
	return file_api_proto_common_common_proto_rawDescGZIP(), []int{6}
}

func (x *Stock) GetStockCode() int64 {
	if x != nil {
		return x.StockCode
	}
	return 0
}

func (x *Stock) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Stock) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Stock) GetIsin() string {
	if x != nil {
		return x.Isin
	}
	return ""
}

func (x *Stock) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

// Price range filter
type PriceRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinPrice      float64                `protobuf:"fixed64,1,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      float64                `protobuf:"fixed64,2,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceRange) Reset() {
	*x = PriceRange{}
	mi := &file_api_proto_common_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceRange) ProtoMessage() {}

func (x *PriceRange) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceRange.ProtoReflect.Descriptor instead.
func (*PriceRange) Descriptor() ([]byte, []int) {
	return file_api_proto_common_common_proto_rawDescGZIP(), []int{7}
}

func (x *PriceRange) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *PriceRange) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

// Health check message
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_common_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_common_common_proto_rawDescGZIP(), []int{8}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     *Timestamp             `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Dependencies  map[string]string      `protobuf:"bytes,5,rep,name=dependencies,proto3" json:"dependencies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Dependency health status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_common_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_common_common_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() *Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthCheckResponse) GetDependencies() map[string]string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

var File_api_proto_common_common_proto protoreflect.FileDescriptor

const file_api_proto_common_common_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/common/common.proto\x12\x06common\";\n" +
	"\tTimestamp\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x03R\aseconds\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\x05R\x05nanos\"|\n" +
	"\x11PaginationRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\x03 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\tR\tsortOrder\"\xc5\x01\n" +
	"\x12PaginationResponse\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_items\x18\x03 \x01(\x03R\n" +
	"totalItems\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\x12\x19\n" +
	"\bhas_next\x18\x05 \x01(\bR\ahasNext\x12!\n" +
	"\fhas_previous\x18\x06 \x01(\bR\vhasPrevious\"\x80\x01\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x03(\tR\adetails\x12/\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x11.common.TimestampR\ttimestamp\"i\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\x05error\x18\x03 \x01(\v2\r.common.ErrorR\x05error\"\a\n" +
	"\x05Empty\"\x91\x01\n" +
	"\x05Stock\x12\x1d\n" +
	"\n" +
	"stock_code\x18\x01 \x01(\x03R\tstockCode\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04isin\x18\x04 \x01(\tR\x04isin\x12!\n" +
	"\fcompany_name\x18\x05 \x01(\tR\vcompanyName\"F\n" +
	"\n" +
	"PriceRange\x12\x1b\n" +
	"\tmin_price\x18\x01 \x01(\x01R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x02 \x01(\x01R\bmaxPrice\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xa8\x02\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12/\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x11.common.TimestampR\ttimestamp\x12Q\n" +
	"\fdependencies\x18\x05 \x03(\v2-.common.HealthCheckResponse.DependenciesEntryR\fdependencies\x1a?\n" +
	"\x11DependenciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x8f\x01\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ORDER_TYPE_MARKET\x10\x01\x12\x14\n" +
	"\x10ORDER_TYPE_LIMIT\x10\x02\x12\x18\n" +
	"\x14ORDER_TYPE_STOP_LOSS\x10\x03\x12\x1f\n" +
	"\x1bORDER_TYPE_STOP_LOSS_MARKET\x10\x04*P\n" +
	"\tOrderSide\x12\x1a\n" +
	"\x16ORDER_SIDE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eORDER_SIDE_BUY\x10\x01\x12\x13\n" +
	"\x0fORDER_SIDE_SELL\x10\x02*\xa2\x02\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ORDER_STATUS_RECEIVED\x10\x01\x12\x1a\n" +
	"\x16ORDER_STATUS_VALIDATED\x10\x02\x12\x18\n" +
	"\x14ORDER_STATUS_PENDING\x10\x03\x12\x1a\n" +
	"\x16ORDER_STATUS_SUBMITTED\x10\x04\x12\x17\n" +
	"\x13ORDER_STATUS_FILLED\x10\x05\x12\x1f\n" +
	"\x1bORDER_STATUS_PARTIAL_FILLED\x10\x06\x12\x19\n" +
	"\x15ORDER_STATUS_REJECTED\x10\a\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\b\x12\x17\n" +
	"\x13ORDER_STATUS_FAILED\x10\t*m\n" +
	"\tSentiment\x12\x19\n" +
	"\x15SENTIMENT_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SENTIMENT_POSITIVE\x10\x01\x12\x15\n" +
	"\x11SENTIMENT_NEUTRAL\x10\x02\x12\x16\n" +
	"\x12SENTIMENT_NEGATIVE\x10\x03*H\n" +
	"\bExchange\x12\x18\n" +
	"\x14EXCHANGE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fEXCHANGE_NSE\x10\x01\x12\x10\n" +
	"\fEXCHANGE_BSE\x10\x02*\x8c\x01\n" +
	"\x0ePositionSizing\x12\x1f\n" +
	"\x1bPOSITION_SIZING_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15POSITION_SIZING_FIXED\x10\x01\x12\x1e\n" +
	"\x1aPOSITION_SIZING_PERCENTAGE\x10\x02\x12\x1e\n" +
	"\x1aPOSITION_SIZING_RISK_BASED\x10\x03B7Z5github.com/RohitIndira/Algo-Treading/api/proto/commonb\x06proto3"

var (
	file_api_proto_common_common_proto_rawDescOnce sync.Once
	file_api_proto_common_common_proto_rawDescData []byte
)

func file_api_proto_common_common_proto_rawDescGZIP() []byte {
	file_api_proto_common_common_proto_rawDescOnce.Do(func() {
		file_api_proto_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_common_common_proto_rawDesc), len(file_api_proto_common_common_proto_rawDesc)))
	})
	return file_api_proto_common_common_proto_rawDescData
}

var file_api_proto_common_common_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_api_proto_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_common_common_proto_goTypes = []any{
	(OrderType)(0),              // 0: common.OrderType
	(OrderSide)(0),              // 1: common.OrderSide
	(OrderStatus)(0),            // 2: common.OrderStatus
	(Sentiment)(0),              // 3: common.Sentiment
	(Exchange)(0),               // 4: common.Exchange
	(PositionSizing)(0),         // 5: common.PositionSizing
	(*Timestamp)(nil),           // 6: common.Timestamp
	(*PaginationRequest)(nil),   // 7: common.PaginationRequest
	(*PaginationResponse)(nil),  // 8: common.PaginationResponse
	(*Error)(nil),               // 9: common.Error
	(*StatusResponse)(nil),      // 10: common.StatusResponse
	(*Empty)(nil),               // 11: common.Empty
	(*Stock)(nil),               // 12: common.Stock
	(*PriceRange)(nil),          // 13: common.PriceRange
	(*HealthCheckRequest)(nil),  // 14: common.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 15: common.HealthCheckResponse
	nil,                         // 16: common.HealthCheckResponse.DependenciesEntry
}
var file_api_proto_common_common_proto_depIdxs = []int32{
	6,  // 0: common.Error.timestamp:type_name -> common.Timestamp
	9,  // 1: common.StatusResponse.error:type_name -> common.Error
	6,  // 2: common.HealthCheckResponse.timestamp:type_name -> common.Timestamp
	16, // 3: common.HealthCheckResponse.dependencies:type_name -> common.HealthCheckResponse.DependenciesEntry
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_common_common_proto_init() }
func file_api_proto_common_common_proto_init() {
	if File_api_proto_common_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_common_common_proto_rawDesc), len(file_api_proto_common_common_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_common_common_proto_goTypes,
		DependencyIndexes: file_api_proto_common_common_proto_depIdxs,
		EnumInfos:         file_api_proto_common_common_proto_enumTypes,
		MessageInfos:      file_api_proto_common_common_proto_msgTypes,
	}.Build()
	File_api_proto_common_common_proto = out.File
	file_api_proto_common_common_proto_goTypes = nil
	file_api_proto_common_common_proto_depIdxs = nil
}
