// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/user_config/user_config.proto

package user_config

import (
	common "github.com/RohitIndira/Algo-Treading/api/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Stop loss type enumeration
type StopLossType int32

const (
	StopLossType_STOP_LOSS_TYPE_UNSPECIFIED StopLossType = 0
	StopLossType_FIXED                      StopLossType = 1 // Fixed stop loss percentage
	StopLossType_TRAILING                   StopLossType = 2 // Trailing stop loss that moves with profit
)

// Enum value maps for StopLossType.
var (
	StopLossType_name = map[int32]string{
		0: "STOP_LOSS_TYPE_UNSPECIFIED",
		1: "FIXED",
		2: "TRAILING",
	}
	StopLossType_value = map[string]int32{
		"STOP_LOSS_TYPE_UNSPECIFIED": 0,
		"FIXED":                      1,
		"TRAILING":                   2,
	}
)

func (x StopLossType) Enum() *StopLossType {
	p := new(StopLossType)
	*p = x
	return p
}

func (x StopLossType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StopLossType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_user_config_user_config_proto_enumTypes[0].Descriptor()
}

func (StopLossType) Type() protoreflect.EnumType {
	return &file_api_proto_user_config_user_config_proto_enumTypes[0]
}

func (x StopLossType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StopLossType.Descriptor instead.
func (StopLossType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_user_config_user_config_proto_rawDescGZIP(), []int{0}
}

// Strategy condition filters
type StrategyConditions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Match ALL news events (overrides all other conditions except impact_score_threshold)
	// Set this to true to create a catch-all strategy
	// Example: User sends "/all" to match every news event
	MatchAllNews bool `protobuf:"varint,1,opt,name=match_all_news,json=matchAllNews,proto3" json:"match_all_news,omitempty"`
	// Impact score threshold (1-10)
	// Even with match_all_news=true, news must meet minimum impact score
	ImpactScoreThreshold int32 `protobuf:"varint,2,opt,name=impact_score_threshold,json=impactScoreThreshold,proto3" json:"impact_score_threshold,omitempty"`
	// Sentiment filters (positive, neutral, negative)
	// Ignored if match_all_news=true
	Sentiments []common.Sentiment `protobuf:"varint,3,rep,packed,name=sentiments,proto3,enum=common.Sentiment" json:"sentiments,omitempty"`
	// News categories to monitor
	// Ignored if match_all_news=true
	Categories []string `protobuf:"bytes,4,rep,name=categories,proto3" json:"categories,omitempty"`
	// Specific stocks to monitor (stock codes)
	// Ignored if match_all_news=true
	StockCodes []int64 `protobuf:"varint,5,rep,packed,name=stock_codes,json=stockCodes,proto3" json:"stock_codes,omitempty"`
	// Price range filter
	// Ignored if match_all_news=true
	PriceRange *common.PriceRange `protobuf:"bytes,6,opt,name=price_range,json=priceRange,proto3" json:"price_range,omitempty"`
	// Minimum trading volume threshold
	// Ignored if match_all_news=true
	VolumeThreshold int64 `protobuf:"varint,7,opt,name=volume_threshold,json=volumeThreshold,proto3" json:"volume_threshold,omitempty"`
	// Percentage change threshold (trigger if stock moves by this %)
	// Ignored if match_all_news=true
	PctChangeThreshold float64 `protobuf:"fixed64,8,opt,name=pct_change_threshold,json=pctChangeThreshold,proto3" json:"pct_change_threshold,omitempty"`
	// Exchanges to monitor
	// Ignored if match_all_news=true
	Exchanges      []common.Exchange                  `protobuf:"varint,9,rep,packed,name=exchanges,proto3,enum=common.Exchange" json:"exchanges,omitempty"`
	MarketCapRange *StrategyConditions_MarketCapRange `protobuf:"bytes,10,opt,name=market_cap_range,json=marketCapRange,proto3" json:"market_cap_range,omitempty"`
	// Depth-based filters
	MinBidQuantity          int64   `protobuf:"varint,11,opt,name=min_bid_quantity,json=minBidQuantity,proto3" json:"min_bid_quantity,omitempty"`
	MinAskQuantity          int64   `protobuf:"varint,12,opt,name=min_ask_quantity,json=minAskQuantity,proto3" json:"min_ask_quantity,omitempty"`
	MaxSpreadPct            float64 `protobuf:"fixed64,13,opt,name=max_spread_pct,json=maxSpreadPct,proto3" json:"max_spread_pct,omitempty"`
	DepthOnly               bool    `protobuf:"varint,14,opt,name=depth_only,json=depthOnly,proto3" json:"depth_only,omitempty"`
	RequireLtpBetweenSpread bool    `protobuf:"varint,15,opt,name=require_ltp_between_spread,json=requireLtpBetweenSpread,proto3" json:"require_ltp_between_spread,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *StrategyConditions) Reset() {
	*x = StrategyConditions{}
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyConditions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyConditions) ProtoMessage() {}

func (x *StrategyConditions) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyConditions.ProtoReflect.Descriptor instead.
func (*StrategyConditions) Descriptor() ([]byte, []int) {
	return file_api_proto_user_config_user_config_proto_rawDescGZIP(), []int{0}
}

func (x *StrategyConditions) GetMatchAllNews() bool {
	if x != nil {
		return x.MatchAllNews
	}
	return false
}

func (x *StrategyConditions) GetImpactScoreThreshold() int32 {
	if x != nil {
		return x.ImpactScoreThreshold
	}
	return 0
}

func (x *StrategyConditions) GetSentiments() []common.Sentiment {
	if x != nil {
		return x.Sentiments
	}
	return nil
}

func (x *StrategyConditions) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *StrategyConditions) GetStockCodes() []int64 {
	if x != nil {
		return x.StockCodes
	}
	return nil
}

func (x *StrategyConditions) GetPriceRange() *common.PriceRange {
	if x != nil {
		return x.PriceRange
	}
	return nil
}

func (x *StrategyConditions) GetVolumeThreshold() int64 {
	if x != nil {
		return x.VolumeThreshold
	}
	return 0
}

func (x *StrategyConditions) GetPctChangeThreshold() float64 {
	if x != nil {
		return x.PctChangeThreshold
	}
	return 0
}

func (x *StrategyConditions) GetExchanges() []common.Exchange {
	if x != nil {
		return x.Exchanges
	}
	return nil
}

func (x *StrategyConditions) GetMarketCapRange() *StrategyConditions_MarketCapRange {
	if x != nil {
		return x.MarketCapRange
	}
	return nil
}

func (x *StrategyConditions) GetMinBidQuantity() int64 {
	if x != nil {
		return x.MinBidQuantity
	}
	return 0
}

func (x *StrategyConditions) GetMinAskQuantity() int64 {
	if x != nil {
		return x.MinAskQuantity
	}
	return 0
}

func (x *StrategyConditions) GetMaxSpreadPct() float64 {
	if x != nil {
		return x.MaxSpreadPct
	}
	return 0
}

func (x *StrategyConditions) GetDepthOnly() bool {
	if x != nil {
		return x.DepthOnly
	}
	return false
}

func (x *StrategyConditions) GetRequireLtpBetweenSpread() bool {
	if x != nil {
		return x.RequireLtpBetweenSpread
	}
	return false
}

// Trade execution configuration
type TradeConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Order type (MARKET, LIMIT, etc.)
	OrderType common.OrderType `protobuf:"varint,1,opt,name=order_type,json=orderType,proto3,enum=common.OrderType" json:"order_type,omitempty"`
	// Fixed quantity to trade
	Quantity int32 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// Maximum position size (in rupees)
	MaxPositionSize float64 `protobuf:"fixed64,3,opt,name=max_position_size,json=maxPositionSize,proto3" json:"max_position_size,omitempty"`
	// Stop loss percentage
	StopLossPct float64 `protobuf:"fixed64,4,opt,name=stop_loss_pct,json=stopLossPct,proto3" json:"stop_loss_pct,omitempty"`
	// Take profit percentage
	TakeProfitPct float64 `protobuf:"fixed64,5,opt,name=take_profit_pct,json=takeProfitPct,proto3" json:"take_profit_pct,omitempty"`
	// Primary exchange for execution
	Exchange common.Exchange `protobuf:"varint,6,opt,name=exchange,proto3,enum=common.Exchange" json:"exchange,omitempty"`
	// Order side (BUY/SELL)
	OrderSide common.OrderSide `protobuf:"varint,7,opt,name=order_side,json=orderSide,proto3,enum=common.OrderSide" json:"order_side,omitempty"`
	// Limit price (for LIMIT orders, optional)
	LimitPrice float64 `protobuf:"fixed64,8,opt,name=limit_price,json=limitPrice,proto3" json:"limit_price,omitempty"`
	// Validity (DAY, IOC, etc.)
	Validity string `protobuf:"bytes,9,opt,name=validity,proto3" json:"validity,omitempty"`
	// Stop loss type (FIXED or TRAILING)
	StopLossType StopLossType `protobuf:"varint,10,opt,name=stop_loss_type,json=stopLossType,proto3,enum=user_config.StopLossType" json:"stop_loss_type,omitempty"`
	// Trailing stop loss percentage (only applies when stop_loss_type=TRAILING)
	// Example: 1.0 means trail by 1% as price moves in favorable direction
	TrailingSlPct float64 `protobuf:"fixed64,11,opt,name=trailing_sl_pct,json=trailingSlPct,proto3" json:"trailing_sl_pct,omitempty"`
	// Product type (INTRADAY, DELIVERY, CASH)
	ProductType   string `protobuf:"bytes,12,opt,name=product_type,json=productType,proto3" json:"product_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeConfig) Reset() {
	*x = TradeConfig{}
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeConfig) ProtoMessage() {}

func (x *TradeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeConfig.ProtoReflect.Descriptor instead.
func (*TradeConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_user_config_user_config_proto_rawDescGZIP(), []int{1}
}

func (x *TradeConfig) GetOrderType() common.OrderType {
	if x != nil {
		return x.OrderType
	}
	return common.OrderType(0)
}

func (x *TradeConfig) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *TradeConfig) GetMaxPositionSize() float64 {
	if x != nil {
		return x.MaxPositionSize
	}
	return 0
}

func (x *TradeConfig) GetStopLossPct() float64 {
	if x != nil {
		return x.StopLossPct
	}
	return 0
}

func (x *TradeConfig) GetTakeProfitPct() float64 {
	if x != nil {
		return x.TakeProfitPct
	}
	return 0
}

func (x *TradeConfig) GetExchange() common.Exchange {
	if x != nil {
		return x.Exchange
	}
	return common.Exchange(0)
}

func (x *TradeConfig) GetOrderSide() common.OrderSide {
	if x != nil {
		return x.OrderSide
	}
	return common.OrderSide(0)
}

func (x *TradeConfig) GetLimitPrice() float64 {
	if x != nil {
		return x.LimitPrice
	}
	return 0
}

func (x *TradeConfig) GetValidity() string {
	if x != nil {
		return x.Validity
	}
	return ""
}

func (x *TradeConfig) GetStopLossType() StopLossType {
	if x != nil {
		return x.StopLossType
	}
	return StopLossType_STOP_LOSS_TYPE_UNSPECIFIED
}

func (x *TradeConfig) GetTrailingSlPct() float64 {
	if x != nil {
		return x.TrailingSlPct
	}
	return 0
}

func (x *TradeConfig) GetProductType() string {
	if x != nil {
		return x.ProductType
	}
	return ""
}

// Risk management limits
type RiskLimits struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of trades per day
	MaxDailyTrades int32 `protobuf:"varint,1,opt,name=max_daily_trades,json=maxDailyTrades,proto3" json:"max_daily_trades,omitempty"`
	// Maximum loss allowed per day (in rupees)
	MaxLossPerDay float64 `protobuf:"fixed64,2,opt,name=max_loss_per_day,json=maxLossPerDay,proto3" json:"max_loss_per_day,omitempty"`
	// Position sizing strategy
	PositionSizing common.PositionSizing `protobuf:"varint,3,opt,name=position_sizing,json=positionSizing,proto3,enum=common.PositionSizing" json:"position_sizing,omitempty"`
	// Maximum portfolio exposure percentage
	MaxPortfolioExposurePct float64 `protobuf:"fixed64,4,opt,name=max_portfolio_exposure_pct,json=maxPortfolioExposurePct,proto3" json:"max_portfolio_exposure_pct,omitempty"`
	// Maximum per-trade risk (in rupees)
	MaxPerTradeRisk float64 `protobuf:"fixed64,5,opt,name=max_per_trade_risk,json=maxPerTradeRisk,proto3" json:"max_per_trade_risk,omitempty"`
	// Enable risk checks
	EnableRiskChecks bool `protobuf:"varint,6,opt,name=enable_risk_checks,json=enableRiskChecks,proto3" json:"enable_risk_checks,omitempty"`
	// Enable auto square-off at market close
	EnableAutoSquareOff bool `protobuf:"varint,7,opt,name=enable_auto_square_off,json=enableAutoSquareOff,proto3" json:"enable_auto_square_off,omitempty"`
	// Auto square-off time (format: "15:05" for 3:05 PM)
	AutoSquareOffTime string `protobuf:"bytes,8,opt,name=auto_square_off_time,json=autoSquareOffTime,proto3" json:"auto_square_off_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RiskLimits) Reset() {
	*x = RiskLimits{}
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskLimits) ProtoMessage() {}

func (x *RiskLimits) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskLimits.ProtoReflect.Descriptor instead.
func (*RiskLimits) Descriptor() ([]byte, []int) {
	return file_api_proto_user_config_user_config_proto_rawDescGZIP(), []int{2}
}

func (x *RiskLimits) GetMaxDailyTrades() int32 {
	if x != nil {
		return x.MaxDailyTrades
	}
	return 0
}

func (x *RiskLimits) GetMaxLossPerDay() float64 {
	if x != nil {
		return x.MaxLossPerDay
	}
	return 0
}

func (x *RiskLimits) GetPositionSizing() common.PositionSizing {
	if x != nil {
		return x.PositionSizing
	}
	return common.PositionSizing(0)
}

func (x *RiskLimits) GetMaxPortfolioExposurePct() float64 {
	if x != nil {
		return x.MaxPortfolioExposurePct
	}
	return 0
}

func (x *RiskLimits) GetMaxPerTradeRisk() float64 {
	if x != nil {
		return x.MaxPerTradeRisk
	}
	return 0
}

func (x *RiskLimits) GetEnableRiskChecks() bool {
	if x != nil {
		return x.EnableRiskChecks
	}
	return false
}

func (x *RiskLimits) GetEnableAutoSquareOff() bool {
	if x != nil {
		return x.EnableAutoSquareOff
	}
	return false
}

func (x *RiskLimits) GetAutoSquareOffTime() string {
	if x != nil {
		return x.AutoSquareOffTime
	}
	return ""
}

// Trading strategy definition
type Strategy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique strategy ID
	StrategyId string `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	// User ID who owns this strategy
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Strategy name
	StrategyName string `protobuf:"bytes,3,opt,name=strategy_name,json=strategyName,proto3" json:"strategy_name,omitempty"`
	// Strategy description
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Is strategy active
	Active bool `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	// Strategy conditions
	Conditions *StrategyConditions `protobuf:"bytes,6,opt,name=conditions,proto3" json:"conditions,omitempty"`
	// Trade configuration
	TradeConfig *TradeConfig `protobuf:"bytes,7,opt,name=trade_config,json=tradeConfig,proto3" json:"trade_config,omitempty"`
	// Risk limits
	RiskLimits *RiskLimits `protobuf:"bytes,8,opt,name=risk_limits,json=riskLimits,proto3" json:"risk_limits,omitempty"`
	// Creation timestamp
	CreatedAt *common.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp
	UpdatedAt *common.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Version for optimistic locking
	Version       int32 `protobuf:"varint,11,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Strategy) Reset() {
	*x = Strategy{}
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Strategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Strategy) ProtoMessage() {}

func (x *Strategy) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Strategy.ProtoReflect.Descriptor instead.
func (*Strategy) Descriptor() ([]byte, []int) {
	return file_api_proto_user_config_user_config_proto_rawDescGZIP(), []int{3}
}

func (x *Strategy) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *Strategy) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Strategy) GetStrategyName() string {
	if x != nil {
		return x.StrategyName
	}
	return ""
}

func (x *Strategy) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Strategy) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Strategy) GetConditions() *StrategyConditions {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *Strategy) GetTradeConfig() *TradeConfig {
	if x != nil {
		return x.TradeConfig
	}
	return nil
}

func (x *Strategy) GetRiskLimits() *RiskLimits {
	if x != nil {
		return x.RiskLimits
	}
	return nil
}

func (x *Strategy) GetCreatedAt() *common.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Strategy) GetUpdatedAt() *common.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Strategy) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type CreateStrategyRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StrategyName        string                 `protobuf:"bytes,2,opt,name=strategy_name,json=strategyName,proto3" json:"strategy_name,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Conditions          *StrategyConditions    `protobuf:"bytes,4,opt,name=conditions,proto3" json:"conditions,omitempty"`
	TradeConfig         *TradeConfig           `protobuf:"bytes,5,opt,name=trade_config,json=tradeConfig,proto3" json:"trade_config,omitempty"`
	RiskLimits          *RiskLimits            `protobuf:"bytes,6,opt,name=risk_limits,json=riskLimits,proto3" json:"risk_limits,omitempty"`
	ActivateImmediately bool                   `protobuf:"varint,7,opt,name=activate_immediately,json=activateImmediately,proto3" json:"activate_immediately,omitempty"`
	BearerToken         string                 `protobuf:"bytes,8,opt,name=bearer_token,json=bearerToken,proto3" json:"bearer_token,omitempty"`
	AppId               string                 `protobuf:"bytes,9,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Source              string                 `protobuf:"bytes,10,opt,name=source,proto3" json:"source,omitempty"`
	// Add these new fields for Indira Securities
	IndiraUserId  string `protobuf:"bytes,11,opt,name=indira_user_id,json=indiraUserId,proto3" json:"indira_user_id,omitempty"` // e.g., "ISPL19122"
	IndiraAppId   string `protobuf:"bytes,12,opt,name=indira_app_id,json=indiraAppId,proto3" json:"indira_app_id,omitempty"`    // Application ID from frontend
	IndiraSource  string `protobuf:"bytes,13,opt,name=indira_source,json=indiraSource,proto3" json:"indira_source,omitempty"`   // "IOS", "AND", or "WEB"
	IndiraToken   string `protobuf:"bytes,14,opt,name=indira_token,json=indiraToken,proto3" json:"indira_token,omitempty"`      // JWT bearer token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStrategyRequest) Reset() {
	*x = CreateStrategyRequest{}
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStrategyRequest) ProtoMessage() {}

func (x *CreateStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStrategyRequest.ProtoReflect.Descriptor instead.
func (*CreateStrategyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_config_user_config_proto_rawDescGZIP(), []int{4}
}

func (x *CreateStrategyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateStrategyRequest) GetStrategyName() string {
	if x != nil {
		return x.StrategyName
	}
	return ""
}

func (x *CreateStrategyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateStrategyRequest) GetConditions() *StrategyConditions {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *CreateStrategyRequest) GetTradeConfig() *TradeConfig {
	if x != nil {
		return x.TradeConfig
	}
	return nil
}

func (x *CreateStrategyRequest) GetRiskLimits() *RiskLimits {
	if x != nil {
		return x.RiskLimits
	}
	return nil
}

func (x *CreateStrategyRequest) GetActivateImmediately() bool {
	if x != nil {
		return x.ActivateImmediately
	}
	return false
}

func (x *CreateStrategyRequest) GetBearerToken() string {
	if x != nil {
		return x.BearerToken
	}
	return ""
}

func (x *CreateStrategyRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *CreateStrategyRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CreateStrategyRequest) GetIndiraUserId() string {
	if x != nil {
		return x.IndiraUserId
	}
	return ""
}

func (x *CreateStrategyRequest) GetIndiraAppId() string {
	if x != nil {
		return x.IndiraAppId
	}
	return ""
}

func (x *CreateStrategyRequest) GetIndiraSource() string {
	if x != nil {
		return x.IndiraSource
	}
	return ""
}

func (x *CreateStrategyRequest) GetIndiraToken() string {
	if x != nil {
		return x.IndiraToken
	}
	return ""
}

type CreateStrategyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Strategy      *Strategy              `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Error         *common.Error          `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStrategyResponse) Reset() {
	*x = CreateStrategyResponse{}
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStrategyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStrategyResponse) ProtoMessage() {}

func (x *CreateStrategyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStrategyResponse.ProtoReflect.Descriptor instead.
func (*CreateStrategyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_config_user_config_proto_rawDescGZIP(), []int{5}
}

func (x *CreateStrategyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateStrategyResponse) GetStrategy() *Strategy {
	if x != nil {
		return x.Strategy
	}
	return nil
}

func (x *CreateStrategyResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Update strategy request
type UpdateStrategyRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StrategyId string                 `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	UserId     string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Optional fields - only provided fields will be updated
	StrategyName *string             `protobuf:"bytes,3,opt,name=strategy_name,json=strategyName,proto3,oneof" json:"strategy_name,omitempty"`
	Description  *string             `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Conditions   *StrategyConditions `protobuf:"bytes,5,opt,name=conditions,proto3,oneof" json:"conditions,omitempty"`
	TradeConfig  *TradeConfig        `protobuf:"bytes,6,opt,name=trade_config,json=tradeConfig,proto3,oneof" json:"trade_config,omitempty"`
	RiskLimits   *RiskLimits         `protobuf:"bytes,7,opt,name=risk_limits,json=riskLimits,proto3,oneof" json:"risk_limits,omitempty"`
	// Version for optimistic locking
	Version       int32 `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStrategyRequest) Reset() {
	*x = UpdateStrategyRequest{}
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStrategyRequest) ProtoMessage() {}

func (x *UpdateStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStrategyRequest.ProtoReflect.Descriptor instead.
func (*UpdateStrategyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_config_user_config_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateStrategyRequest) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *UpdateStrategyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateStrategyRequest) GetStrategyName() string {
	if x != nil && x.StrategyName != nil {
		return *x.StrategyName
	}
	return ""
}

func (x *UpdateStrategyRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateStrategyRequest) GetConditions() *StrategyConditions {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *UpdateStrategyRequest) GetTradeConfig() *TradeConfig {
	if x != nil {
		return x.TradeConfig
	}
	return nil
}

func (x *UpdateStrategyRequest) GetRiskLimits() *RiskLimits {
	if x != nil {
		return x.RiskLimits
	}
	return nil
}

func (x *UpdateStrategyRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UpdateStrategyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Strategy      *Strategy              `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Error         *common.Error          `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStrategyResponse) Reset() {
	*x = UpdateStrategyResponse{}
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStrategyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStrategyResponse) ProtoMessage() {}

func (x *UpdateStrategyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStrategyResponse.ProtoReflect.Descriptor instead.
func (*UpdateStrategyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_config_user_config_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateStrategyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateStrategyResponse) GetStrategy() *Strategy {
	if x != nil {
		return x.Strategy
	}
	return nil
}

func (x *UpdateStrategyResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Delete strategy request
type DeleteStrategyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    string                 `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // For authorization
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStrategyRequest) Reset() {
	*x = DeleteStrategyRequest{}
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStrategyRequest) ProtoMessage() {}

func (x *DeleteStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStrategyRequest.ProtoReflect.Descriptor instead.
func (*DeleteStrategyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_config_user_config_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteStrategyRequest) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *DeleteStrategyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteStrategyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         *common.Error          `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStrategyResponse) Reset() {
	*x = DeleteStrategyResponse{}
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStrategyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStrategyResponse) ProtoMessage() {}

func (x *DeleteStrategyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStrategyResponse.ProtoReflect.Descriptor instead.
func (*DeleteStrategyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_config_user_config_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteStrategyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteStrategyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteStrategyResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Get strategy request
type GetStrategyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    string                 `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // For authorization
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStrategyRequest) Reset() {
	*x = GetStrategyRequest{}
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStrategyRequest) ProtoMessage() {}

func (x *GetStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStrategyRequest.ProtoReflect.Descriptor instead.
func (*GetStrategyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_config_user_config_proto_rawDescGZIP(), []int{10}
}

func (x *GetStrategyRequest) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *GetStrategyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetStrategyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Strategy      *Strategy              `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Error         *common.Error          `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStrategyResponse) Reset() {
	*x = GetStrategyResponse{}
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStrategyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStrategyResponse) ProtoMessage() {}

func (x *GetStrategyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStrategyResponse.ProtoReflect.Descriptor instead.
func (*GetStrategyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_config_user_config_proto_rawDescGZIP(), []int{11}
}

func (x *GetStrategyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetStrategyResponse) GetStrategy() *Strategy {
	if x != nil {
		return x.Strategy
	}
	return nil
}

func (x *GetStrategyResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// List user strategies request
type ListUserStrategiesRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	UserId        string                    `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActiveOnly    bool                      `protobuf:"varint,2,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"` // Filter to only active strategies
	Pagination    *common.PaginationRequest `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserStrategiesRequest) Reset() {
	*x = ListUserStrategiesRequest{}
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserStrategiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserStrategiesRequest) ProtoMessage() {}

func (x *ListUserStrategiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserStrategiesRequest.ProtoReflect.Descriptor instead.
func (*ListUserStrategiesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_config_user_config_proto_rawDescGZIP(), []int{12}
}

func (x *ListUserStrategiesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListUserStrategiesRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

func (x *ListUserStrategiesRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListUserStrategiesResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Success       bool                       `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Strategies    []*Strategy                `protobuf:"bytes,2,rep,name=strategies,proto3" json:"strategies,omitempty"`
	Pagination    *common.PaginationResponse `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Error         *common.Error              `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserStrategiesResponse) Reset() {
	*x = ListUserStrategiesResponse{}
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserStrategiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserStrategiesResponse) ProtoMessage() {}

func (x *ListUserStrategiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserStrategiesResponse.ProtoReflect.Descriptor instead.
func (*ListUserStrategiesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_config_user_config_proto_rawDescGZIP(), []int{13}
}

func (x *ListUserStrategiesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListUserStrategiesResponse) GetStrategies() []*Strategy {
	if x != nil {
		return x.Strategies
	}
	return nil
}

func (x *ListUserStrategiesResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListUserStrategiesResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Activate strategy request
type ActivateStrategyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    string                 `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // For authorization
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateStrategyRequest) Reset() {
	*x = ActivateStrategyRequest{}
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateStrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateStrategyRequest) ProtoMessage() {}

func (x *ActivateStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateStrategyRequest.ProtoReflect.Descriptor instead.
func (*ActivateStrategyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_config_user_config_proto_rawDescGZIP(), []int{14}
}

func (x *ActivateStrategyRequest) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *ActivateStrategyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ActivateStrategyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Strategy      *Strategy              `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Error         *common.Error          `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateStrategyResponse) Reset() {
	*x = ActivateStrategyResponse{}
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateStrategyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateStrategyResponse) ProtoMessage() {}

func (x *ActivateStrategyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateStrategyResponse.ProtoReflect.Descriptor instead.
func (*ActivateStrategyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_config_user_config_proto_rawDescGZIP(), []int{15}
}

func (x *ActivateStrategyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActivateStrategyResponse) GetStrategy() *Strategy {
	if x != nil {
		return x.Strategy
	}
	return nil
}

func (x *ActivateStrategyResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Deactivate strategy request
type DeactivateStrategyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    string                 `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // For authorization
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateStrategyRequest) Reset() {
	*x = DeactivateStrategyRequest{}
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateStrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateStrategyRequest) ProtoMessage() {}

func (x *DeactivateStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateStrategyRequest.ProtoReflect.Descriptor instead.
func (*DeactivateStrategyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_config_user_config_proto_rawDescGZIP(), []int{16}
}

func (x *DeactivateStrategyRequest) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *DeactivateStrategyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeactivateStrategyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Strategy      *Strategy              `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Error         *common.Error          `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateStrategyResponse) Reset() {
	*x = DeactivateStrategyResponse{}
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateStrategyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateStrategyResponse) ProtoMessage() {}

func (x *DeactivateStrategyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateStrategyResponse.ProtoReflect.Descriptor instead.
func (*DeactivateStrategyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_config_user_config_proto_rawDescGZIP(), []int{17}
}

func (x *DeactivateStrategyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeactivateStrategyResponse) GetStrategy() *Strategy {
	if x != nil {
		return x.Strategy
	}
	return nil
}

func (x *DeactivateStrategyResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Get strategies by IDs (for internal services)
type GetStrategiesByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyIds   []string               `protobuf:"bytes,1,rep,name=strategy_ids,json=strategyIds,proto3" json:"strategy_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStrategiesByIDsRequest) Reset() {
	*x = GetStrategiesByIDsRequest{}
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStrategiesByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStrategiesByIDsRequest) ProtoMessage() {}

func (x *GetStrategiesByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStrategiesByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetStrategiesByIDsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_config_user_config_proto_rawDescGZIP(), []int{18}
}

func (x *GetStrategiesByIDsRequest) GetStrategyIds() []string {
	if x != nil {
		return x.StrategyIds
	}
	return nil
}

type GetStrategiesByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Strategies    []*Strategy            `protobuf:"bytes,2,rep,name=strategies,proto3" json:"strategies,omitempty"`
	Error         *common.Error          `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStrategiesByIDsResponse) Reset() {
	*x = GetStrategiesByIDsResponse{}
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStrategiesByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStrategiesByIDsResponse) ProtoMessage() {}

func (x *GetStrategiesByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStrategiesByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetStrategiesByIDsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_config_user_config_proto_rawDescGZIP(), []int{19}
}

func (x *GetStrategiesByIDsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetStrategiesByIDsResponse) GetStrategies() []*Strategy {
	if x != nil {
		return x.Strategies
	}
	return nil
}

func (x *GetStrategiesByIDsResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type UpdateUserCredentialsRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	UserId      string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BearerToken string                 `protobuf:"bytes,2,opt,name=bearer_token,json=bearerToken,proto3" json:"bearer_token,omitempty"`
	AppId       string                 `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Source      string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	// Add these new fields for Indira Securities
	IndiraUserId  string `protobuf:"bytes,5,opt,name=indira_user_id,json=indiraUserId,proto3" json:"indira_user_id,omitempty"` // e.g., "ISPL19122"
	IndiraAppId   string `protobuf:"bytes,6,opt,name=indira_app_id,json=indiraAppId,proto3" json:"indira_app_id,omitempty"`    // Application ID from frontend
	IndiraSource  string `protobuf:"bytes,7,opt,name=indira_source,json=indiraSource,proto3" json:"indira_source,omitempty"`   // "IOS", "AND", or "WEB"
	IndiraToken   string `protobuf:"bytes,8,opt,name=indira_token,json=indiraToken,proto3" json:"indira_token,omitempty"`      // JWT bearer token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserCredentialsRequest) Reset() {
	*x = UpdateUserCredentialsRequest{}
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserCredentialsRequest) ProtoMessage() {}

func (x *UpdateUserCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserCredentialsRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_config_user_config_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateUserCredentialsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserCredentialsRequest) GetBearerToken() string {
	if x != nil {
		return x.BearerToken
	}
	return ""
}

func (x *UpdateUserCredentialsRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *UpdateUserCredentialsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *UpdateUserCredentialsRequest) GetIndiraUserId() string {
	if x != nil {
		return x.IndiraUserId
	}
	return ""
}

func (x *UpdateUserCredentialsRequest) GetIndiraAppId() string {
	if x != nil {
		return x.IndiraAppId
	}
	return ""
}

func (x *UpdateUserCredentialsRequest) GetIndiraSource() string {
	if x != nil {
		return x.IndiraSource
	}
	return ""
}

func (x *UpdateUserCredentialsRequest) GetIndiraToken() string {
	if x != nil {
		return x.IndiraToken
	}
	return ""
}

type GetUserCredentialsResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Success     bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BearerToken string                 `protobuf:"bytes,2,opt,name=bearer_token,json=bearerToken,proto3" json:"bearer_token,omitempty"`
	AppId       string                 `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Source      string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Error       *common.Error          `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	// Add these new fields for Indira Securities
	IndiraUserId  string `protobuf:"bytes,6,opt,name=indira_user_id,json=indiraUserId,proto3" json:"indira_user_id,omitempty"` // e.g., "ISPL19122"
	IndiraAppId   string `protobuf:"bytes,7,opt,name=indira_app_id,json=indiraAppId,proto3" json:"indira_app_id,omitempty"`    // Application ID from frontend
	IndiraSource  string `protobuf:"bytes,8,opt,name=indira_source,json=indiraSource,proto3" json:"indira_source,omitempty"`   // "IOS", "AND", or "WEB"
	IndiraToken   string `protobuf:"bytes,9,opt,name=indira_token,json=indiraToken,proto3" json:"indira_token,omitempty"`      // JWT bearer token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCredentialsResponse) Reset() {
	*x = GetUserCredentialsResponse{}
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCredentialsResponse) ProtoMessage() {}

func (x *GetUserCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCredentialsResponse.ProtoReflect.Descriptor instead.
func (*GetUserCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_config_user_config_proto_rawDescGZIP(), []int{21}
}

func (x *GetUserCredentialsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetUserCredentialsResponse) GetBearerToken() string {
	if x != nil {
		return x.BearerToken
	}
	return ""
}

func (x *GetUserCredentialsResponse) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetUserCredentialsResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GetUserCredentialsResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetUserCredentialsResponse) GetIndiraUserId() string {
	if x != nil {
		return x.IndiraUserId
	}
	return ""
}

func (x *GetUserCredentialsResponse) GetIndiraAppId() string {
	if x != nil {
		return x.IndiraAppId
	}
	return ""
}

func (x *GetUserCredentialsResponse) GetIndiraSource() string {
	if x != nil {
		return x.IndiraSource
	}
	return ""
}

func (x *GetUserCredentialsResponse) GetIndiraToken() string {
	if x != nil {
		return x.IndiraToken
	}
	return ""
}

type UpdateUserCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *common.Error          `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserCredentialsResponse) Reset() {
	*x = UpdateUserCredentialsResponse{}
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserCredentialsResponse) ProtoMessage() {}

func (x *UpdateUserCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserCredentialsResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_config_user_config_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateUserCredentialsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateUserCredentialsResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetUserCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCredentialsRequest) Reset() {
	*x = GetUserCredentialsRequest{}
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCredentialsRequest) ProtoMessage() {}

func (x *GetUserCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCredentialsRequest.ProtoReflect.Descriptor instead.
func (*GetUserCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_config_user_config_proto_rawDescGZIP(), []int{23}
}

func (x *GetUserCredentialsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Market cap range filter (in crores)
// Ignored if match_all_news=true
type StrategyConditions_MarketCapRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinMcap       float64                `protobuf:"fixed64,1,opt,name=min_mcap,json=minMcap,proto3" json:"min_mcap,omitempty"` // Minimum market cap in crores
	MaxMcap       float64                `protobuf:"fixed64,2,opt,name=max_mcap,json=maxMcap,proto3" json:"max_mcap,omitempty"` // Maximum market cap in crores
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategyConditions_MarketCapRange) Reset() {
	*x = StrategyConditions_MarketCapRange{}
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyConditions_MarketCapRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyConditions_MarketCapRange) ProtoMessage() {}

func (x *StrategyConditions_MarketCapRange) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_config_user_config_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyConditions_MarketCapRange.ProtoReflect.Descriptor instead.
func (*StrategyConditions_MarketCapRange) Descriptor() ([]byte, []int) {
	return file_api_proto_user_config_user_config_proto_rawDescGZIP(), []int{0, 0}
}

func (x *StrategyConditions_MarketCapRange) GetMinMcap() float64 {
	if x != nil {
		return x.MinMcap
	}
	return 0
}

func (x *StrategyConditions_MarketCapRange) GetMaxMcap() float64 {
	if x != nil {
		return x.MaxMcap
	}
	return 0
}

var File_api_proto_user_config_user_config_proto protoreflect.FileDescriptor

const file_api_proto_user_config_user_config_proto_rawDesc = "" +
	"\n" +
	"'api/proto/user_config/user_config.proto\x12\vuser_config\x1a\x1dapi/proto/common/common.proto\"\x9e\x06\n" +
	"\x12StrategyConditions\x12$\n" +
	"\x0ematch_all_news\x18\x01 \x01(\bR\fmatchAllNews\x124\n" +
	"\x16impact_score_threshold\x18\x02 \x01(\x05R\x14impactScoreThreshold\x121\n" +
	"\n" +
	"sentiments\x18\x03 \x03(\x0e2\x11.common.SentimentR\n" +
	"sentiments\x12\x1e\n" +
	"\n" +
	"categories\x18\x04 \x03(\tR\n" +
	"categories\x12\x1f\n" +
	"\vstock_codes\x18\x05 \x03(\x03R\n" +
	"stockCodes\x123\n" +
	"\vprice_range\x18\x06 \x01(\v2\x12.common.PriceRangeR\n" +
	"priceRange\x12)\n" +
	"\x10volume_threshold\x18\a \x01(\x03R\x0fvolumeThreshold\x120\n" +
	"\x14pct_change_threshold\x18\b \x01(\x01R\x12pctChangeThreshold\x12.\n" +
	"\texchanges\x18\t \x03(\x0e2\x10.common.ExchangeR\texchanges\x12X\n" +
	"\x10market_cap_range\x18\n" +
	" \x01(\v2..user_config.StrategyConditions.MarketCapRangeR\x0emarketCapRange\x12(\n" +
	"\x10min_bid_quantity\x18\v \x01(\x03R\x0eminBidQuantity\x12(\n" +
	"\x10min_ask_quantity\x18\f \x01(\x03R\x0eminAskQuantity\x12$\n" +
	"\x0emax_spread_pct\x18\r \x01(\x01R\fmaxSpreadPct\x12\x1d\n" +
	"\n" +
	"depth_only\x18\x0e \x01(\bR\tdepthOnly\x12;\n" +
	"\x1arequire_ltp_between_spread\x18\x0f \x01(\bR\x17requireLtpBetweenSpread\x1aF\n" +
	"\x0eMarketCapRange\x12\x19\n" +
	"\bmin_mcap\x18\x01 \x01(\x01R\aminMcap\x12\x19\n" +
	"\bmax_mcap\x18\x02 \x01(\x01R\amaxMcap\"\xfc\x03\n" +
	"\vTradeConfig\x120\n" +
	"\n" +
	"order_type\x18\x01 \x01(\x0e2\x11.common.OrderTypeR\torderType\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12*\n" +
	"\x11max_position_size\x18\x03 \x01(\x01R\x0fmaxPositionSize\x12\"\n" +
	"\rstop_loss_pct\x18\x04 \x01(\x01R\vstopLossPct\x12&\n" +
	"\x0ftake_profit_pct\x18\x05 \x01(\x01R\rtakeProfitPct\x12,\n" +
	"\bexchange\x18\x06 \x01(\x0e2\x10.common.ExchangeR\bexchange\x120\n" +
	"\n" +
	"order_side\x18\a \x01(\x0e2\x11.common.OrderSideR\torderSide\x12\x1f\n" +
	"\vlimit_price\x18\b \x01(\x01R\n" +
	"limitPrice\x12\x1a\n" +
	"\bvalidity\x18\t \x01(\tR\bvalidity\x12?\n" +
	"\x0estop_loss_type\x18\n" +
	" \x01(\x0e2\x19.user_config.StopLossTypeR\fstopLossType\x12&\n" +
	"\x0ftrailing_sl_pct\x18\v \x01(\x01R\rtrailingSlPct\x12!\n" +
	"\fproduct_type\x18\f \x01(\tR\vproductType\"\x9e\x03\n" +
	"\n" +
	"RiskLimits\x12(\n" +
	"\x10max_daily_trades\x18\x01 \x01(\x05R\x0emaxDailyTrades\x12'\n" +
	"\x10max_loss_per_day\x18\x02 \x01(\x01R\rmaxLossPerDay\x12?\n" +
	"\x0fposition_sizing\x18\x03 \x01(\x0e2\x16.common.PositionSizingR\x0epositionSizing\x12;\n" +
	"\x1amax_portfolio_exposure_pct\x18\x04 \x01(\x01R\x17maxPortfolioExposurePct\x12+\n" +
	"\x12max_per_trade_risk\x18\x05 \x01(\x01R\x0fmaxPerTradeRisk\x12,\n" +
	"\x12enable_risk_checks\x18\x06 \x01(\bR\x10enableRiskChecks\x123\n" +
	"\x16enable_auto_square_off\x18\a \x01(\bR\x13enableAutoSquareOff\x12/\n" +
	"\x14auto_square_off_time\x18\b \x01(\tR\x11autoSquareOffTime\"\xd9\x03\n" +
	"\bStrategy\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\tR\n" +
	"strategyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rstrategy_name\x18\x03 \x01(\tR\fstrategyName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\x12?\n" +
	"\n" +
	"conditions\x18\x06 \x01(\v2\x1f.user_config.StrategyConditionsR\n" +
	"conditions\x12;\n" +
	"\ftrade_config\x18\a \x01(\v2\x18.user_config.TradeConfigR\vtradeConfig\x128\n" +
	"\vrisk_limits\x18\b \x01(\v2\x17.user_config.RiskLimitsR\n" +
	"riskLimits\x120\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x11.common.TimestampR\tcreatedAt\x120\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x11.common.TimestampR\tupdatedAt\x12\x18\n" +
	"\aversion\x18\v \x01(\x05R\aversion\"\xc6\x04\n" +
	"\x15CreateStrategyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rstrategy_name\x18\x02 \x01(\tR\fstrategyName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12?\n" +
	"\n" +
	"conditions\x18\x04 \x01(\v2\x1f.user_config.StrategyConditionsR\n" +
	"conditions\x12;\n" +
	"\ftrade_config\x18\x05 \x01(\v2\x18.user_config.TradeConfigR\vtradeConfig\x128\n" +
	"\vrisk_limits\x18\x06 \x01(\v2\x17.user_config.RiskLimitsR\n" +
	"riskLimits\x121\n" +
	"\x14activate_immediately\x18\a \x01(\bR\x13activateImmediately\x12!\n" +
	"\fbearer_token\x18\b \x01(\tR\vbearerToken\x12\x15\n" +
	"\x06app_id\x18\t \x01(\tR\x05appId\x12\x16\n" +
	"\x06source\x18\n" +
	" \x01(\tR\x06source\x12$\n" +
	"\x0eindira_user_id\x18\v \x01(\tR\findiraUserId\x12\"\n" +
	"\rindira_app_id\x18\f \x01(\tR\vindiraAppId\x12#\n" +
	"\rindira_source\x18\r \x01(\tR\findiraSource\x12!\n" +
	"\findira_token\x18\x0e \x01(\tR\vindiraToken\"\x8a\x01\n" +
	"\x16CreateStrategyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x121\n" +
	"\bstrategy\x18\x02 \x01(\v2\x15.user_config.StrategyR\bstrategy\x12#\n" +
	"\x05error\x18\x03 \x01(\v2\r.common.ErrorR\x05error\"\xd5\x03\n" +
	"\x15UpdateStrategyRequest\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\tR\n" +
	"strategyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12(\n" +
	"\rstrategy_name\x18\x03 \x01(\tH\x00R\fstrategyName\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12D\n" +
	"\n" +
	"conditions\x18\x05 \x01(\v2\x1f.user_config.StrategyConditionsH\x02R\n" +
	"conditions\x88\x01\x01\x12@\n" +
	"\ftrade_config\x18\x06 \x01(\v2\x18.user_config.TradeConfigH\x03R\vtradeConfig\x88\x01\x01\x12=\n" +
	"\vrisk_limits\x18\a \x01(\v2\x17.user_config.RiskLimitsH\x04R\n" +
	"riskLimits\x88\x01\x01\x12\x18\n" +
	"\aversion\x18\b \x01(\x05R\aversionB\x10\n" +
	"\x0e_strategy_nameB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_conditionsB\x0f\n" +
	"\r_trade_configB\x0e\n" +
	"\f_risk_limits\"\x8a\x01\n" +
	"\x16UpdateStrategyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x121\n" +
	"\bstrategy\x18\x02 \x01(\v2\x15.user_config.StrategyR\bstrategy\x12#\n" +
	"\x05error\x18\x03 \x01(\v2\r.common.ErrorR\x05error\"Q\n" +
	"\x15DeleteStrategyRequest\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\tR\n" +
	"strategyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"q\n" +
	"\x16DeleteStrategyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\x05error\x18\x03 \x01(\v2\r.common.ErrorR\x05error\"N\n" +
	"\x12GetStrategyRequest\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\tR\n" +
	"strategyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x87\x01\n" +
	"\x13GetStrategyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x121\n" +
	"\bstrategy\x18\x02 \x01(\v2\x15.user_config.StrategyR\bstrategy\x12#\n" +
	"\x05error\x18\x03 \x01(\v2\r.common.ErrorR\x05error\"\x90\x01\n" +
	"\x19ListUserStrategiesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vactive_only\x18\x02 \x01(\bR\n" +
	"activeOnly\x129\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\"\xce\x01\n" +
	"\x1aListUserStrategiesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x125\n" +
	"\n" +
	"strategies\x18\x02 \x03(\v2\x15.user_config.StrategyR\n" +
	"strategies\x12:\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x1a.common.PaginationResponseR\n" +
	"pagination\x12#\n" +
	"\x05error\x18\x04 \x01(\v2\r.common.ErrorR\x05error\"S\n" +
	"\x17ActivateStrategyRequest\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\tR\n" +
	"strategyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x8c\x01\n" +
	"\x18ActivateStrategyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x121\n" +
	"\bstrategy\x18\x02 \x01(\v2\x15.user_config.StrategyR\bstrategy\x12#\n" +
	"\x05error\x18\x03 \x01(\v2\r.common.ErrorR\x05error\"U\n" +
	"\x19DeactivateStrategyRequest\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\tR\n" +
	"strategyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x8e\x01\n" +
	"\x1aDeactivateStrategyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x121\n" +
	"\bstrategy\x18\x02 \x01(\v2\x15.user_config.StrategyR\bstrategy\x12#\n" +
	"\x05error\x18\x03 \x01(\v2\r.common.ErrorR\x05error\">\n" +
	"\x19GetStrategiesByIDsRequest\x12!\n" +
	"\fstrategy_ids\x18\x01 \x03(\tR\vstrategyIds\"\x92\x01\n" +
	"\x1aGetStrategiesByIDsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x125\n" +
	"\n" +
	"strategies\x18\x02 \x03(\v2\x15.user_config.StrategyR\n" +
	"strategies\x12#\n" +
	"\x05error\x18\x03 \x01(\v2\r.common.ErrorR\x05error\"\x9b\x02\n" +
	"\x1cUpdateUserCredentialsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fbearer_token\x18\x02 \x01(\tR\vbearerToken\x12\x15\n" +
	"\x06app_id\x18\x03 \x01(\tR\x05appId\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12$\n" +
	"\x0eindira_user_id\x18\x05 \x01(\tR\findiraUserId\x12\"\n" +
	"\rindira_app_id\x18\x06 \x01(\tR\vindiraAppId\x12#\n" +
	"\rindira_source\x18\a \x01(\tR\findiraSource\x12!\n" +
	"\findira_token\x18\b \x01(\tR\vindiraToken\"\xbf\x02\n" +
	"\x1aGetUserCredentialsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fbearer_token\x18\x02 \x01(\tR\vbearerToken\x12\x15\n" +
	"\x06app_id\x18\x03 \x01(\tR\x05appId\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12#\n" +
	"\x05error\x18\x05 \x01(\v2\r.common.ErrorR\x05error\x12$\n" +
	"\x0eindira_user_id\x18\x06 \x01(\tR\findiraUserId\x12\"\n" +
	"\rindira_app_id\x18\a \x01(\tR\vindiraAppId\x12#\n" +
	"\rindira_source\x18\b \x01(\tR\findiraSource\x12!\n" +
	"\findira_token\x18\t \x01(\tR\vindiraToken\"^\n" +
	"\x1dUpdateUserCredentialsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\x05error\x18\x02 \x01(\v2\r.common.ErrorR\x05error\"4\n" +
	"\x19GetUserCredentialsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId*G\n" +
	"\fStopLossType\x12\x1e\n" +
	"\x1aSTOP_LOSS_TYPE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05FIXED\x10\x01\x12\f\n" +
	"\bTRAILING\x10\x022\xab\b\n" +
	"\x11UserConfigService\x12Y\n" +
	"\x0eCreateStrategy\x12\".user_config.CreateStrategyRequest\x1a#.user_config.CreateStrategyResponse\x12Y\n" +
	"\x0eUpdateStrategy\x12\".user_config.UpdateStrategyRequest\x1a#.user_config.UpdateStrategyResponse\x12Y\n" +
	"\x0eDeleteStrategy\x12\".user_config.DeleteStrategyRequest\x1a#.user_config.DeleteStrategyResponse\x12P\n" +
	"\vGetStrategy\x12\x1f.user_config.GetStrategyRequest\x1a .user_config.GetStrategyResponse\x12e\n" +
	"\x12ListUserStrategies\x12&.user_config.ListUserStrategiesRequest\x1a'.user_config.ListUserStrategiesResponse\x12_\n" +
	"\x10ActivateStrategy\x12$.user_config.ActivateStrategyRequest\x1a%.user_config.ActivateStrategyResponse\x12e\n" +
	"\x12DeactivateStrategy\x12&.user_config.DeactivateStrategyRequest\x1a'.user_config.DeactivateStrategyResponse\x12e\n" +
	"\x12GetStrategiesByIDs\x12&.user_config.GetStrategiesByIDsRequest\x1a'.user_config.GetStrategiesByIDsResponse\x12n\n" +
	"\x15UpdateUserCredentials\x12).user_config.UpdateUserCredentialsRequest\x1a*.user_config.UpdateUserCredentialsResponse\x12e\n" +
	"\x12GetUserCredentials\x12&.user_config.GetUserCredentialsRequest\x1a'.user_config.GetUserCredentialsResponse\x12F\n" +
	"\vHealthCheck\x12\x1a.common.HealthCheckRequest\x1a\x1b.common.HealthCheckResponseB<Z:github.com/RohitIndira/Algo-Treading/api/proto/user_configb\x06proto3"

var (
	file_api_proto_user_config_user_config_proto_rawDescOnce sync.Once
	file_api_proto_user_config_user_config_proto_rawDescData []byte
)

func file_api_proto_user_config_user_config_proto_rawDescGZIP() []byte {
	file_api_proto_user_config_user_config_proto_rawDescOnce.Do(func() {
		file_api_proto_user_config_user_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_user_config_user_config_proto_rawDesc), len(file_api_proto_user_config_user_config_proto_rawDesc)))
	})
	return file_api_proto_user_config_user_config_proto_rawDescData
}

var file_api_proto_user_config_user_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_user_config_user_config_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_api_proto_user_config_user_config_proto_goTypes = []any{
	(StopLossType)(0),                         // 0: user_config.StopLossType
	(*StrategyConditions)(nil),                // 1: user_config.StrategyConditions
	(*TradeConfig)(nil),                       // 2: user_config.TradeConfig
	(*RiskLimits)(nil),                        // 3: user_config.RiskLimits
	(*Strategy)(nil),                          // 4: user_config.Strategy
	(*CreateStrategyRequest)(nil),             // 5: user_config.CreateStrategyRequest
	(*CreateStrategyResponse)(nil),            // 6: user_config.CreateStrategyResponse
	(*UpdateStrategyRequest)(nil),             // 7: user_config.UpdateStrategyRequest
	(*UpdateStrategyResponse)(nil),            // 8: user_config.UpdateStrategyResponse
	(*DeleteStrategyRequest)(nil),             // 9: user_config.DeleteStrategyRequest
	(*DeleteStrategyResponse)(nil),            // 10: user_config.DeleteStrategyResponse
	(*GetStrategyRequest)(nil),                // 11: user_config.GetStrategyRequest
	(*GetStrategyResponse)(nil),               // 12: user_config.GetStrategyResponse
	(*ListUserStrategiesRequest)(nil),         // 13: user_config.ListUserStrategiesRequest
	(*ListUserStrategiesResponse)(nil),        // 14: user_config.ListUserStrategiesResponse
	(*ActivateStrategyRequest)(nil),           // 15: user_config.ActivateStrategyRequest
	(*ActivateStrategyResponse)(nil),          // 16: user_config.ActivateStrategyResponse
	(*DeactivateStrategyRequest)(nil),         // 17: user_config.DeactivateStrategyRequest
	(*DeactivateStrategyResponse)(nil),        // 18: user_config.DeactivateStrategyResponse
	(*GetStrategiesByIDsRequest)(nil),         // 19: user_config.GetStrategiesByIDsRequest
	(*GetStrategiesByIDsResponse)(nil),        // 20: user_config.GetStrategiesByIDsResponse
	(*UpdateUserCredentialsRequest)(nil),      // 21: user_config.UpdateUserCredentialsRequest
	(*GetUserCredentialsResponse)(nil),        // 22: user_config.GetUserCredentialsResponse
	(*UpdateUserCredentialsResponse)(nil),     // 23: user_config.UpdateUserCredentialsResponse
	(*GetUserCredentialsRequest)(nil),         // 24: user_config.GetUserCredentialsRequest
	(*StrategyConditions_MarketCapRange)(nil), // 25: user_config.StrategyConditions.MarketCapRange
	(common.Sentiment)(0),                     // 26: common.Sentiment
	(*common.PriceRange)(nil),                 // 27: common.PriceRange
	(common.Exchange)(0),                      // 28: common.Exchange
	(common.OrderType)(0),                     // 29: common.OrderType
	(common.OrderSide)(0),                     // 30: common.OrderSide
	(common.PositionSizing)(0),                // 31: common.PositionSizing
	(*common.Timestamp)(nil),                  // 32: common.Timestamp
	(*common.Error)(nil),                      // 33: common.Error
	(*common.PaginationRequest)(nil),          // 34: common.PaginationRequest
	(*common.PaginationResponse)(nil),         // 35: common.PaginationResponse
	(*common.HealthCheckRequest)(nil),         // 36: common.HealthCheckRequest
	(*common.HealthCheckResponse)(nil),        // 37: common.HealthCheckResponse
}
var file_api_proto_user_config_user_config_proto_depIdxs = []int32{
	26, // 0: user_config.StrategyConditions.sentiments:type_name -> common.Sentiment
	27, // 1: user_config.StrategyConditions.price_range:type_name -> common.PriceRange
	28, // 2: user_config.StrategyConditions.exchanges:type_name -> common.Exchange
	25, // 3: user_config.StrategyConditions.market_cap_range:type_name -> user_config.StrategyConditions.MarketCapRange
	29, // 4: user_config.TradeConfig.order_type:type_name -> common.OrderType
	28, // 5: user_config.TradeConfig.exchange:type_name -> common.Exchange
	30, // 6: user_config.TradeConfig.order_side:type_name -> common.OrderSide
	0,  // 7: user_config.TradeConfig.stop_loss_type:type_name -> user_config.StopLossType
	31, // 8: user_config.RiskLimits.position_sizing:type_name -> common.PositionSizing
	1,  // 9: user_config.Strategy.conditions:type_name -> user_config.StrategyConditions
	2,  // 10: user_config.Strategy.trade_config:type_name -> user_config.TradeConfig
	3,  // 11: user_config.Strategy.risk_limits:type_name -> user_config.RiskLimits
	32, // 12: user_config.Strategy.created_at:type_name -> common.Timestamp
	32, // 13: user_config.Strategy.updated_at:type_name -> common.Timestamp
	1,  // 14: user_config.CreateStrategyRequest.conditions:type_name -> user_config.StrategyConditions
	2,  // 15: user_config.CreateStrategyRequest.trade_config:type_name -> user_config.TradeConfig
	3,  // 16: user_config.CreateStrategyRequest.risk_limits:type_name -> user_config.RiskLimits
	4,  // 17: user_config.CreateStrategyResponse.strategy:type_name -> user_config.Strategy
	33, // 18: user_config.CreateStrategyResponse.error:type_name -> common.Error
	1,  // 19: user_config.UpdateStrategyRequest.conditions:type_name -> user_config.StrategyConditions
	2,  // 20: user_config.UpdateStrategyRequest.trade_config:type_name -> user_config.TradeConfig
	3,  // 21: user_config.UpdateStrategyRequest.risk_limits:type_name -> user_config.RiskLimits
	4,  // 22: user_config.UpdateStrategyResponse.strategy:type_name -> user_config.Strategy
	33, // 23: user_config.UpdateStrategyResponse.error:type_name -> common.Error
	33, // 24: user_config.DeleteStrategyResponse.error:type_name -> common.Error
	4,  // 25: user_config.GetStrategyResponse.strategy:type_name -> user_config.Strategy
	33, // 26: user_config.GetStrategyResponse.error:type_name -> common.Error
	34, // 27: user_config.ListUserStrategiesRequest.pagination:type_name -> common.PaginationRequest
	4,  // 28: user_config.ListUserStrategiesResponse.strategies:type_name -> user_config.Strategy
	35, // 29: user_config.ListUserStrategiesResponse.pagination:type_name -> common.PaginationResponse
	33, // 30: user_config.ListUserStrategiesResponse.error:type_name -> common.Error
	4,  // 31: user_config.ActivateStrategyResponse.strategy:type_name -> user_config.Strategy
	33, // 32: user_config.ActivateStrategyResponse.error:type_name -> common.Error
	4,  // 33: user_config.DeactivateStrategyResponse.strategy:type_name -> user_config.Strategy
	33, // 34: user_config.DeactivateStrategyResponse.error:type_name -> common.Error
	4,  // 35: user_config.GetStrategiesByIDsResponse.strategies:type_name -> user_config.Strategy
	33, // 36: user_config.GetStrategiesByIDsResponse.error:type_name -> common.Error
	33, // 37: user_config.GetUserCredentialsResponse.error:type_name -> common.Error
	33, // 38: user_config.UpdateUserCredentialsResponse.error:type_name -> common.Error
	5,  // 39: user_config.UserConfigService.CreateStrategy:input_type -> user_config.CreateStrategyRequest
	7,  // 40: user_config.UserConfigService.UpdateStrategy:input_type -> user_config.UpdateStrategyRequest
	9,  // 41: user_config.UserConfigService.DeleteStrategy:input_type -> user_config.DeleteStrategyRequest
	11, // 42: user_config.UserConfigService.GetStrategy:input_type -> user_config.GetStrategyRequest
	13, // 43: user_config.UserConfigService.ListUserStrategies:input_type -> user_config.ListUserStrategiesRequest
	15, // 44: user_config.UserConfigService.ActivateStrategy:input_type -> user_config.ActivateStrategyRequest
	17, // 45: user_config.UserConfigService.DeactivateStrategy:input_type -> user_config.DeactivateStrategyRequest
	19, // 46: user_config.UserConfigService.GetStrategiesByIDs:input_type -> user_config.GetStrategiesByIDsRequest
	21, // 47: user_config.UserConfigService.UpdateUserCredentials:input_type -> user_config.UpdateUserCredentialsRequest
	24, // 48: user_config.UserConfigService.GetUserCredentials:input_type -> user_config.GetUserCredentialsRequest
	36, // 49: user_config.UserConfigService.HealthCheck:input_type -> common.HealthCheckRequest
	6,  // 50: user_config.UserConfigService.CreateStrategy:output_type -> user_config.CreateStrategyResponse
	8,  // 51: user_config.UserConfigService.UpdateStrategy:output_type -> user_config.UpdateStrategyResponse
	10, // 52: user_config.UserConfigService.DeleteStrategy:output_type -> user_config.DeleteStrategyResponse
	12, // 53: user_config.UserConfigService.GetStrategy:output_type -> user_config.GetStrategyResponse
	14, // 54: user_config.UserConfigService.ListUserStrategies:output_type -> user_config.ListUserStrategiesResponse
	16, // 55: user_config.UserConfigService.ActivateStrategy:output_type -> user_config.ActivateStrategyResponse
	18, // 56: user_config.UserConfigService.DeactivateStrategy:output_type -> user_config.DeactivateStrategyResponse
	20, // 57: user_config.UserConfigService.GetStrategiesByIDs:output_type -> user_config.GetStrategiesByIDsResponse
	23, // 58: user_config.UserConfigService.UpdateUserCredentials:output_type -> user_config.UpdateUserCredentialsResponse
	22, // 59: user_config.UserConfigService.GetUserCredentials:output_type -> user_config.GetUserCredentialsResponse
	37, // 60: user_config.UserConfigService.HealthCheck:output_type -> common.HealthCheckResponse
	50, // [50:61] is the sub-list for method output_type
	39, // [39:50] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_api_proto_user_config_user_config_proto_init() }
func file_api_proto_user_config_user_config_proto_init() {
	if File_api_proto_user_config_user_config_proto != nil {
		return
	}
	file_api_proto_user_config_user_config_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_user_config_user_config_proto_rawDesc), len(file_api_proto_user_config_user_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_user_config_user_config_proto_goTypes,
		DependencyIndexes: file_api_proto_user_config_user_config_proto_depIdxs,
		EnumInfos:         file_api_proto_user_config_user_config_proto_enumTypes,
		MessageInfos:      file_api_proto_user_config_user_config_proto_msgTypes,
	}.Build()
	File_api_proto_user_config_user_config_proto = out.File
	file_api_proto_user_config_user_config_proto_goTypes = nil
	file_api_proto_user_config_user_config_proto_depIdxs = nil
}
