// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: api/proto/user_config/user_config.proto

package user_config

import (
	context "context"
	common "github.com/RohitIndira/Algo-Treading/api/proto/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserConfigService_CreateStrategy_FullMethodName        = "/user_config.UserConfigService/CreateStrategy"
	UserConfigService_UpdateStrategy_FullMethodName        = "/user_config.UserConfigService/UpdateStrategy"
	UserConfigService_DeleteStrategy_FullMethodName        = "/user_config.UserConfigService/DeleteStrategy"
	UserConfigService_GetStrategy_FullMethodName           = "/user_config.UserConfigService/GetStrategy"
	UserConfigService_ListUserStrategies_FullMethodName    = "/user_config.UserConfigService/ListUserStrategies"
	UserConfigService_ActivateStrategy_FullMethodName      = "/user_config.UserConfigService/ActivateStrategy"
	UserConfigService_DeactivateStrategy_FullMethodName    = "/user_config.UserConfigService/DeactivateStrategy"
	UserConfigService_GetStrategiesByIDs_FullMethodName    = "/user_config.UserConfigService/GetStrategiesByIDs"
	UserConfigService_UpdateUserCredentials_FullMethodName = "/user_config.UserConfigService/UpdateUserCredentials"
	UserConfigService_GetUserCredentials_FullMethodName    = "/user_config.UserConfigService/GetUserCredentials"
	UserConfigService_HealthCheck_FullMethodName           = "/user_config.UserConfigService/HealthCheck"
)

// UserConfigServiceClient is the client API for UserConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// User Configuration Service
// Manages user trading strategies and preferences
type UserConfigServiceClient interface {
	// Create a new trading strategy
	CreateStrategy(ctx context.Context, in *CreateStrategyRequest, opts ...grpc.CallOption) (*CreateStrategyResponse, error)
	// Update an existing strategy
	UpdateStrategy(ctx context.Context, in *UpdateStrategyRequest, opts ...grpc.CallOption) (*UpdateStrategyResponse, error)
	// Delete a strategy
	DeleteStrategy(ctx context.Context, in *DeleteStrategyRequest, opts ...grpc.CallOption) (*DeleteStrategyResponse, error)
	// Get a specific strategy
	GetStrategy(ctx context.Context, in *GetStrategyRequest, opts ...grpc.CallOption) (*GetStrategyResponse, error)
	// List all strategies for a user
	ListUserStrategies(ctx context.Context, in *ListUserStrategiesRequest, opts ...grpc.CallOption) (*ListUserStrategiesResponse, error)
	// Activate a strategy
	ActivateStrategy(ctx context.Context, in *ActivateStrategyRequest, opts ...grpc.CallOption) (*ActivateStrategyResponse, error)
	// Deactivate a strategy
	DeactivateStrategy(ctx context.Context, in *DeactivateStrategyRequest, opts ...grpc.CallOption) (*DeactivateStrategyResponse, error)
	// Get user strategies in bulk (for internal services)
	GetStrategiesByIDs(ctx context.Context, in *GetStrategiesByIDsRequest, opts ...grpc.CallOption) (*GetStrategiesByIDsResponse, error)
	// Update user credentials (bearer token, app_id, source)
	UpdateUserCredentials(ctx context.Context, in *UpdateUserCredentialsRequest, opts ...grpc.CallOption) (*UpdateUserCredentialsResponse, error)
	// Get user credentials for order execution
	GetUserCredentials(ctx context.Context, in *GetUserCredentialsRequest, opts ...grpc.CallOption) (*GetUserCredentialsResponse, error)
	// Health check
	HealthCheck(ctx context.Context, in *common.HealthCheckRequest, opts ...grpc.CallOption) (*common.HealthCheckResponse, error)
}

type userConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserConfigServiceClient(cc grpc.ClientConnInterface) UserConfigServiceClient {
	return &userConfigServiceClient{cc}
}

func (c *userConfigServiceClient) CreateStrategy(ctx context.Context, in *CreateStrategyRequest, opts ...grpc.CallOption) (*CreateStrategyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStrategyResponse)
	err := c.cc.Invoke(ctx, UserConfigService_CreateStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userConfigServiceClient) UpdateStrategy(ctx context.Context, in *UpdateStrategyRequest, opts ...grpc.CallOption) (*UpdateStrategyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStrategyResponse)
	err := c.cc.Invoke(ctx, UserConfigService_UpdateStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userConfigServiceClient) DeleteStrategy(ctx context.Context, in *DeleteStrategyRequest, opts ...grpc.CallOption) (*DeleteStrategyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteStrategyResponse)
	err := c.cc.Invoke(ctx, UserConfigService_DeleteStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userConfigServiceClient) GetStrategy(ctx context.Context, in *GetStrategyRequest, opts ...grpc.CallOption) (*GetStrategyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStrategyResponse)
	err := c.cc.Invoke(ctx, UserConfigService_GetStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userConfigServiceClient) ListUserStrategies(ctx context.Context, in *ListUserStrategiesRequest, opts ...grpc.CallOption) (*ListUserStrategiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserStrategiesResponse)
	err := c.cc.Invoke(ctx, UserConfigService_ListUserStrategies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userConfigServiceClient) ActivateStrategy(ctx context.Context, in *ActivateStrategyRequest, opts ...grpc.CallOption) (*ActivateStrategyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateStrategyResponse)
	err := c.cc.Invoke(ctx, UserConfigService_ActivateStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userConfigServiceClient) DeactivateStrategy(ctx context.Context, in *DeactivateStrategyRequest, opts ...grpc.CallOption) (*DeactivateStrategyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeactivateStrategyResponse)
	err := c.cc.Invoke(ctx, UserConfigService_DeactivateStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userConfigServiceClient) GetStrategiesByIDs(ctx context.Context, in *GetStrategiesByIDsRequest, opts ...grpc.CallOption) (*GetStrategiesByIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStrategiesByIDsResponse)
	err := c.cc.Invoke(ctx, UserConfigService_GetStrategiesByIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userConfigServiceClient) UpdateUserCredentials(ctx context.Context, in *UpdateUserCredentialsRequest, opts ...grpc.CallOption) (*UpdateUserCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserCredentialsResponse)
	err := c.cc.Invoke(ctx, UserConfigService_UpdateUserCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userConfigServiceClient) GetUserCredentials(ctx context.Context, in *GetUserCredentialsRequest, opts ...grpc.CallOption) (*GetUserCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserCredentialsResponse)
	err := c.cc.Invoke(ctx, UserConfigService_GetUserCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userConfigServiceClient) HealthCheck(ctx context.Context, in *common.HealthCheckRequest, opts ...grpc.CallOption) (*common.HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.HealthCheckResponse)
	err := c.cc.Invoke(ctx, UserConfigService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserConfigServiceServer is the server API for UserConfigService service.
// All implementations must embed UnimplementedUserConfigServiceServer
// for forward compatibility.
//
// User Configuration Service
// Manages user trading strategies and preferences
type UserConfigServiceServer interface {
	// Create a new trading strategy
	CreateStrategy(context.Context, *CreateStrategyRequest) (*CreateStrategyResponse, error)
	// Update an existing strategy
	UpdateStrategy(context.Context, *UpdateStrategyRequest) (*UpdateStrategyResponse, error)
	// Delete a strategy
	DeleteStrategy(context.Context, *DeleteStrategyRequest) (*DeleteStrategyResponse, error)
	// Get a specific strategy
	GetStrategy(context.Context, *GetStrategyRequest) (*GetStrategyResponse, error)
	// List all strategies for a user
	ListUserStrategies(context.Context, *ListUserStrategiesRequest) (*ListUserStrategiesResponse, error)
	// Activate a strategy
	ActivateStrategy(context.Context, *ActivateStrategyRequest) (*ActivateStrategyResponse, error)
	// Deactivate a strategy
	DeactivateStrategy(context.Context, *DeactivateStrategyRequest) (*DeactivateStrategyResponse, error)
	// Get user strategies in bulk (for internal services)
	GetStrategiesByIDs(context.Context, *GetStrategiesByIDsRequest) (*GetStrategiesByIDsResponse, error)
	// Update user credentials (bearer token, app_id, source)
	UpdateUserCredentials(context.Context, *UpdateUserCredentialsRequest) (*UpdateUserCredentialsResponse, error)
	// Get user credentials for order execution
	GetUserCredentials(context.Context, *GetUserCredentialsRequest) (*GetUserCredentialsResponse, error)
	// Health check
	HealthCheck(context.Context, *common.HealthCheckRequest) (*common.HealthCheckResponse, error)
	mustEmbedUnimplementedUserConfigServiceServer()
}

// UnimplementedUserConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserConfigServiceServer struct{}

func (UnimplementedUserConfigServiceServer) CreateStrategy(context.Context, *CreateStrategyRequest) (*CreateStrategyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateStrategy not implemented")
}
func (UnimplementedUserConfigServiceServer) UpdateStrategy(context.Context, *UpdateStrategyRequest) (*UpdateStrategyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStrategy not implemented")
}
func (UnimplementedUserConfigServiceServer) DeleteStrategy(context.Context, *DeleteStrategyRequest) (*DeleteStrategyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteStrategy not implemented")
}
func (UnimplementedUserConfigServiceServer) GetStrategy(context.Context, *GetStrategyRequest) (*GetStrategyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStrategy not implemented")
}
func (UnimplementedUserConfigServiceServer) ListUserStrategies(context.Context, *ListUserStrategiesRequest) (*ListUserStrategiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserStrategies not implemented")
}
func (UnimplementedUserConfigServiceServer) ActivateStrategy(context.Context, *ActivateStrategyRequest) (*ActivateStrategyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateStrategy not implemented")
}
func (UnimplementedUserConfigServiceServer) DeactivateStrategy(context.Context, *DeactivateStrategyRequest) (*DeactivateStrategyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeactivateStrategy not implemented")
}
func (UnimplementedUserConfigServiceServer) GetStrategiesByIDs(context.Context, *GetStrategiesByIDsRequest) (*GetStrategiesByIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStrategiesByIDs not implemented")
}
func (UnimplementedUserConfigServiceServer) UpdateUserCredentials(context.Context, *UpdateUserCredentialsRequest) (*UpdateUserCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserCredentials not implemented")
}
func (UnimplementedUserConfigServiceServer) GetUserCredentials(context.Context, *GetUserCredentialsRequest) (*GetUserCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserCredentials not implemented")
}
func (UnimplementedUserConfigServiceServer) HealthCheck(context.Context, *common.HealthCheckRequest) (*common.HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedUserConfigServiceServer) mustEmbedUnimplementedUserConfigServiceServer() {}
func (UnimplementedUserConfigServiceServer) testEmbeddedByValue()                           {}

// UnsafeUserConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserConfigServiceServer will
// result in compilation errors.
type UnsafeUserConfigServiceServer interface {
	mustEmbedUnimplementedUserConfigServiceServer()
}

func RegisterUserConfigServiceServer(s grpc.ServiceRegistrar, srv UserConfigServiceServer) {
	// If the following call panics, it indicates UnimplementedUserConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserConfigService_ServiceDesc, srv)
}

func _UserConfigService_CreateStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserConfigServiceServer).CreateStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserConfigService_CreateStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserConfigServiceServer).CreateStrategy(ctx, req.(*CreateStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserConfigService_UpdateStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserConfigServiceServer).UpdateStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserConfigService_UpdateStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserConfigServiceServer).UpdateStrategy(ctx, req.(*UpdateStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserConfigService_DeleteStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserConfigServiceServer).DeleteStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserConfigService_DeleteStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserConfigServiceServer).DeleteStrategy(ctx, req.(*DeleteStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserConfigService_GetStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserConfigServiceServer).GetStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserConfigService_GetStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserConfigServiceServer).GetStrategy(ctx, req.(*GetStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserConfigService_ListUserStrategies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserStrategiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserConfigServiceServer).ListUserStrategies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserConfigService_ListUserStrategies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserConfigServiceServer).ListUserStrategies(ctx, req.(*ListUserStrategiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserConfigService_ActivateStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserConfigServiceServer).ActivateStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserConfigService_ActivateStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserConfigServiceServer).ActivateStrategy(ctx, req.(*ActivateStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserConfigService_DeactivateStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserConfigServiceServer).DeactivateStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserConfigService_DeactivateStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserConfigServiceServer).DeactivateStrategy(ctx, req.(*DeactivateStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserConfigService_GetStrategiesByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStrategiesByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserConfigServiceServer).GetStrategiesByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserConfigService_GetStrategiesByIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserConfigServiceServer).GetStrategiesByIDs(ctx, req.(*GetStrategiesByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserConfigService_UpdateUserCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserConfigServiceServer).UpdateUserCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserConfigService_UpdateUserCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserConfigServiceServer).UpdateUserCredentials(ctx, req.(*UpdateUserCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserConfigService_GetUserCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserConfigServiceServer).GetUserCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserConfigService_GetUserCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserConfigServiceServer).GetUserCredentials(ctx, req.(*GetUserCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserConfigService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserConfigServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserConfigService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserConfigServiceServer).HealthCheck(ctx, req.(*common.HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserConfigService_ServiceDesc is the grpc.ServiceDesc for UserConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user_config.UserConfigService",
	HandlerType: (*UserConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStrategy",
			Handler:    _UserConfigService_CreateStrategy_Handler,
		},
		{
			MethodName: "UpdateStrategy",
			Handler:    _UserConfigService_UpdateStrategy_Handler,
		},
		{
			MethodName: "DeleteStrategy",
			Handler:    _UserConfigService_DeleteStrategy_Handler,
		},
		{
			MethodName: "GetStrategy",
			Handler:    _UserConfigService_GetStrategy_Handler,
		},
		{
			MethodName: "ListUserStrategies",
			Handler:    _UserConfigService_ListUserStrategies_Handler,
		},
		{
			MethodName: "ActivateStrategy",
			Handler:    _UserConfigService_ActivateStrategy_Handler,
		},
		{
			MethodName: "DeactivateStrategy",
			Handler:    _UserConfigService_DeactivateStrategy_Handler,
		},
		{
			MethodName: "GetStrategiesByIDs",
			Handler:    _UserConfigService_GetStrategiesByIDs_Handler,
		},
		{
			MethodName: "UpdateUserCredentials",
			Handler:    _UserConfigService_UpdateUserCredentials_Handler,
		},
		{
			MethodName: "GetUserCredentials",
			Handler:    _UserConfigService_GetUserCredentials_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _UserConfigService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/user_config/user_config.proto",
}
